<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="d-xl-flex">

                        <div class="w-100">
                            <div class="p-lg-1">
                                <div id="intro" class="mb-5">
                                    <h4 class="mt-0 mb-4">How to delete your account</h4>
                                        
                                    <p>
                                        <?php echo $config['site_name']; ?> allows you to delete your account if you no longer want to use our service<br>
                                        but note that all content that was posted on the platform will be permanently removed and the action cannot be undone!
                                        <br><br>

                                        Removing your account is a very easy step.<br>
                                        Navigate to your profile settings -> scrool down to delete account.<br>
                                        Enter your password to confirm you're the owner of the account then press continue...
                                        <div id="delete" class="mb-5">
                                            <h4 class="mt-0 mb-4">Removing Account</h4>
                                            <img src="<?php echo help('st/images/delection.png');?>" style="width:100%;height:100%;"><br>
                                        </div>
                                    </p>
                                </div>
                            </div> <!-- end padding-->
                        </div>

                        <!-- Start right-side-nav -->
                        <div class="d-none d-xl-block">
                            <div class="right-side-nav">
                                <ul class="nav nav-pills flex-column">
                                    <li class="nav-item">
                                        <a href="#intro" class="nav-link active">Removing Account</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!--end card body-->
            </div> <!-- end card-->
        </div>
    </div>
    <!-- end row -->
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8462913288699097"
     crossorigin="anonymous"></script>
<!-- Help-Center -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8462913288699097"
     data-ad-slot="9094817199"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>