<?php

$context['comments']  = array();
$c_comments           = new comments();

$tot_com = $cpanel->totalComments();
$tot_com_likes  = $cpanel->totalCommentsLikes();
$tot_com_reply  = $cpanel->totalCommentsReply();
$tot_com_reply_likes  = $cpanel->totalCommentsReplyLikes();

$link = '';
$ui = (!empty($_GET['ui-id'])) ? $_GET['ui-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? $cpanel::secure($_GET['query']) : '';
$filter_type    = '';
$t_users = T_USERS;
$search_link = '&';
$rang_link_href = '?';
$t_comments  = T_COMMENTS_REPLY;
$cpanel::$db->pageLimit  = 20;

# the comments
if (!empty($filter_keyword)) {
    $cpanel::$db->join("`$t_users` u",'p.`user_id` = u.`user_id`','INNER');

    if (is_numeric($filter_keyword)) {
        $cpanel::$db->where('p.`id`',"$filter_keyword");
    } else {
        $cpanel::$db->where('p.`text`',"%$filter_keyword%",'LIKE');
    }

	$c_comments = $cpanel::$db->orderBy('p.`id`', 'DESC')->paginate("`$t_comments` p", $ui,array(
        'p.`id`',
        'p.`text`',
        'p.`time`',
        'u.avatar',
        'u.username',
        'u.verified',
        'u.active'
    ));
} else {
	$cpanel::$db->join("`$t_users` u",'p.`user_id` = u.`user_id`','INNER');
    $c_comments = $cpanel::$db->orderBy('p.`id`', 'DESC')->paginate("`$t_comments` p", $ui,array(
        'p.`id`',
        'p.`text`',
        'p.`time`',
        'u.avatar',
        'u.username',
        'u.verified',
        'u.active'
    ));
}

$rang_link = $link;
if (!empty($this_start) && !empty($this_end)) {
    $link .= "&range=".$cpanel::secure($_GET['range']);
    $cpanel::$db->where('time',$this_start,'>=')->where('time',$this_end,'<=');
}
$sort_link = $link;
$sort_array = array('DESC_i' => array('user_id' , 'DESC'),
                    'ASC_i'  => array('user_id' , 'ASC'),
                    'DESC_u' => array('username' , 'DESC'),
                    'ASC_u'  => array('username' , 'ASC'));
if (!empty($_GET['sort']) && in_array($_GET['sort'], array_keys($sort_array))) {
    $cpanel::$db->orderBy($sort_array[$_GET['sort']][0],$sort_array[$_GET['sort']][1]);
    $link .= "&sort=".$cpanel::secure($_GET['sort']);
    $rang_link .= "&sort=".$cpanel::secure($_GET['sort']);
}
else{
    $_GET['sort'] = 'DESC_i';
    $cpanel::$db->orderBy('user_id', 'DESC');
}

///COMMENTS DATA CHART BASED ON THIS YEAR

// Post Comments
$chart = 'This Year';
$comments_yearly_charts = array('This Year');
if (!empty($_GET['chart']) && in_array($_GET['chart'], $comments_yearly_charts)) {
	$chart = $_GET['chart'];
}

if ($chart == 'This Year') {
    $chart_type = 'This Year';

    $this_year_start = strtotime("1 January ".date('Y')." 12:00am");
	$when_this_year_end = strtotime("31 December ".date('Y')." 11:59pm");

    $array_eye = array('01' => 0 ,'02' => 0 ,'03' => 0 ,'04' => 0 ,'05' => 0 ,'06' => 0 ,'07' => 0 ,'08' => 0 ,'09' => 0 ,'10' => 0 ,'11' => 0 ,'12' => 0);
    $yearly_comments_array = $array_eye;

    $yearly_coments_data = $cpanel::$db->where('time',$this_year_start,'>=')->where('time',$when_this_year_end,'<=')->get(T_POST_COMMENTS,null,array('time'));
    foreach ($yearly_coments_data as $key => $value) {
		$hour = date('m',$value->time);
		if (in_array($hour, array_keys($yearly_comments_array))) {
			$yearly_comments_array[$hour] += 1; 
		}
	}

    $comments_yearly_data = implode(', ', $yearly_comments_array);
    $yearly_coments_data = array();
    $yearly_comments_array = array();
    
}

// Post Comments Replies
if ($chart == 'This Year') {
    $chart_type = 'This Year';

    $this_year_start = strtotime("1 January ".date('Y')." 12:00am");
	$when_this_year_end = strtotime("31 December ".date('Y')." 11:59pm");

    $array_eye = array('01' => 0 ,'02' => 0 ,'03' => 0 ,'04' => 0 ,'05' => 0 ,'06' => 0 ,'07' => 0 ,'08' => 0 ,'09' => 0 ,'10' => 0 ,'11' => 0 ,'12' => 0);
    $yearly_comments_array = $array_eye;

    $y_comments_replies = $cpanel::$db->where('time',$this_year_start,'>=')->where('time',$when_this_year_end,'<=')->get(T_COMMENTS_REPLY,null,array('time'));
    foreach ($y_comments_replies as $key => $value) {
		$hour = date('m',$value->time);
		if (in_array($hour, array_keys($yearly_comments_array))) {
			$yearly_comments_array[$hour] += 1; 
		}
	}

    $yearly_comments_replies = implode(', ', $yearly_comments_array);
    $y_comments_replies      = array();
    $yearly_comments_array   = array();
    
}

// Post Comments Liked
if ($chart == 'This Year') {
    $chart_type = 'This Year';

    $this_year_start = strtotime("1 January ".date('Y')." 12:00am");
	$when_this_year_end = strtotime("31 December ".date('Y')." 11:59pm");

    $array_eye = array('01' => 0 ,'02' => 0 ,'03' => 0 ,'04' => 0 ,'05' => 0 ,'06' => 0 ,'07' => 0 ,'08' => 0 ,'09' => 0 ,'10' => 0 ,'11' => 0 ,'12' => 0);
    $yearly_comments_array = $array_eye;

    $y_comments_liked = $cpanel::$db->where('time',$this_year_start,'>=')->where('time',$when_this_year_end,'<=')->get(T_COMMENTS_LIKES,null,array('time'));
    foreach ($y_comments_liked as $key => $value) {
		$hour = date('m',$value->time);
		if (in_array($hour, array_keys($yearly_comments_array))) {
			$yearly_comments_array[$hour] += 1; 
		}
	}

    $yearly_comments_liked = implode(', ', $yearly_comments_array);
    $y_comments_liked      = array();
    $yearly_comments_array   = array();
    
}

// Post Comments Replies Liked
if ($chart == 'This Year') {
    $chart_type = 'This Year';

    $this_year_start = strtotime("1 January ".date('Y')." 12:00am");
	$when_this_year_end = strtotime("31 December ".date('Y')." 11:59pm");

    $array_eye = array('01' => 0 ,'02' => 0 ,'03' => 0 ,'04' => 0 ,'05' => 0 ,'06' => 0 ,'07' => 0 ,'08' => 0 ,'09' => 0 ,'10' => 0 ,'11' => 0 ,'12' => 0);
    $yearly_comments_array = $array_eye;

    $y_comments_rep_liked = $cpanel::$db->where('time',$this_year_start,'>=')->where('time',$when_this_year_end,'<=')->get(T_COMMENTS_REPLY_LIKES,null,array('time'));
    foreach ($y_comments_rep_liked as $key => $value) {
		$hour = date('m',$value->time);
		if (in_array($hour, array_keys($yearly_comments_array))) {
			$yearly_comments_array[$hour] += 1; 
		}
	}

    $y_coms_rep_liked       = implode(', ', $yearly_comments_array);
    $y_comments_rep_liked   = array();
    $yearly_comments_array  = array();
    
}

$mode = 'day';
if (!empty($_COOKIE['mode']) && $_COOKIE['mode'] == 'night') {
    $mode = 'night';
}

if (($ui > $cpanel::$db->totalPages) && !empty($_GET['ui-id'])) {
    header("Location: " . cpanel('comments-reply'));
    exit();
}

?>
<div class="row justify-content-between align-items-center mb-5">
    <div class="col flex-shrink-0 mb-5 mb-md-0">
        <h1 class="display-4 mb-0">Comments Replies</h1>
        <div class="text-muted">
            Members post comments replies are managed in this dictionary!
        </div>
    </div>
</div>
<!-- Colored status cards-->
<div class="row gx-5">
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-info border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $tot_com; ?></div>
                        <div class="card-text">Total Comments</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/instagram.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-pink border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $tot_com_likes; ?></div>
                        <div class="card-text">Comments Liked</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/comments-like.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-warning border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $tot_com_reply; ?></div>
                        <div class="card-text">Comments Replies</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/response.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-pink border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $tot_com_reply_likes; ?></div>
                        <div class="card-text">Replies Liked</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/message-love.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>

</div>


<div class="row gx-5">
    <!-- Yearly comments chart -->
    <div class="col-xl-12 mb-5">
        <div class="card card-raised h-100 border-start border-<?php echo $me['dash_color']; ?> border-4">
            <div class="card-header bg-white px-4">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="me-4">
                            <h2 class="card-title mb-0">Comments Statistics</h2>
                            <div class="card-subtitle">Post comments data chart based on this whole year ok. dam
                            </div>
                        </div>
                        <div class="d-flex gap-2 me-n2">
                            <img src="<?php echo cpanel('si/img/icons/histogram.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                        </div>
                    </div>
                </div>
                <div class="card-body p-4">
                    <div id="yearly-comments-stats"  style="min-width: 100%;"></div>
                </div>
            </div>
        </div>


<!-- Revenue breakdown-->
    <div class="col-lg-12 mb-5">
        <div class="card card-raised h-100 border-start border-<?php echo $me['dash_color']; ?> border-4">
            <div class="card-header bg-white px-4">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="me-4">
                        <form method="get" action="<?php echo cpanel('comments-reply'); ?>">
                            <div class="row">
                                <div class="col-md-10">
                                    <div class="form-group form-float">
                                        <div class="form-line">
                                            <label class="form-label search-form">Search for users comments by their content</label>
                                            <input type="text" name="query" id="query" class="form-control" value="<?php echo($filter_keyword); ?>" autocomplete="off">
                                        </div>
                                    </div>
                                  </div>
                                  <div class="col-md-1">
                                     <div class="form-group form-float">
                                        <div class="form-line">
                                            <label class="form-label" for="priceto">&nbsp;</label>
                                            <button class="btn btn-outline-primary" id="Search">Search</button>
                                        </div>
                                     </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                    <div class="d-flex gap-2 me-n2 mb-n4">
                        <label class="form-label" for="priceto">&nbsp;</label>
                        <img src="<?php echo cpanel('si/img/icons/comment.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                    </div>
                </div>
            </div>
            <div class="card-body p-4">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        <div class="form-check">
                                            <input class="form-check-input check-all" id="check-all" type="checkbox"/>
                                            <label class="form-check-label" for="check-all"></label>
                                        </div>
                                    </th>

                                    <th>ID</th>
                                    <th>Profile</th>
                                    <th>comment</th>
                                    <th>Time</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                    if (!empty($c_comments)) {
                                        foreach ($c_comments as $key => $context['comment']) {
                                            $context['comment'] = o2array($context['comment']);
                                            echo $cpanel->Senction('comments-reply/list');
                                        }
                                    }  
                                ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="float-start">
                        <?php echo "Showing $ui out of " . $cpanel::$db->totalPages; ?> Pages
                    </div>
                    <div class="float-end">
                        <nav>
                            <ul class="pagination">
                                <li>
                                    <a class="text-decoration-none firstpage" href="<?php echo cpanel('comments-reply?ui-id=1').$link; ?>" data-ajax="?path=comments-reply&ui-id=1<?php echo($link); ?>">
                                        <i class="material-icons">first_page</i>
                                    </a>
                                </li>
                                <?php if ($ui > 1) {  ?>
                                <li>
                                    <a class="text-decoration-none previouspage" href="<?php echo cpanel('comments-reply?ui-id=' . ($ui - 1)).$link; ?>" data-ajax="?path=comments-reply&ui-id=<?php echo($ui - 1) ?><?php echo($link); ?>">
                                        <i class="material-icons">chevron_left</i>
                                    </a>
                                </li>
                                <?php  } ?>
                                <?php 
                                $nums       = 0;
                                $nums_uis = ($ui > 4) ? ($ui - 4) : $ui;
                                for ($i=$nums_uis; $i <= $cpanel::$db->totalPages; $i++) { 
                                    if ($nums < 8) {
                                ?>
                                <li class="<?php echo ($ui == $i) ? 'active' : ''; ?>">
                                    <a class="text-decoration-none" href="<?php echo cpanel('comments-reply?ui-id=' . ($i)).$link; ?>" data-ajax="?path=comments-reply&ui-id=<?php echo($i) ?><?php echo($link); ?>" class="waves-effect">
                                        <?php echo $i ?>   
                                    </a>
                                </li>
                                <?php } $nums++; }?>
                                <?php if ($cpanel::$db->totalPages > $ui) { ?>
                                <li>
                                    <a class="text-decoration-none nextpage" href="<?php echo cpanel('comments-reply?ui-id=' . ($ui + 1)).$link; ?>" data-ajax="?path=comments-reply&ui-id=<?php echo($ui + 1) ?><?php echo($link); ?>">
                                        <i class="material-icons">chevron_right</i>
                                    </a>
                                </li>
                                <?php } ?>
                                <li>
                                    <a class="text-decoration-none lastpage" href="<?php echo cpanel('comments-reply?ui-id=' . ($cpanel::$db->totalPages)).$link; ?>" data-ajax="?path=comments-reply&ui-id=<?php echo($cpanel::$db->totalPages) ?><?php echo($link); ?>">
                                        <i class="material-icons">last_page</i>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-lg-3 col-md-3">
                            <button type="button" class="btn btn btn-outline-primary delete-selected d-block" disabled>Take Down<span></span></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

</div>

<!-- Delete Single User -->
<div class="modal fade" id="DeleteModal" tabindex="-1" aria-labelledby="exampleModalCenteredLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenteredLabel">Delete Comment!</h5>
            </div>
            <div class="modal-body">Are you sure you want to delete this user's comment?</div>
            <div class="modal-footer">
                <button class="btn btn-outline-primary me-2" type="button" data-bs-dismiss="modal">Nope</button>
                <button class="btn btn-outline-danger" type="button">Yes Delete</button>
            </div>
        </div>
    </div>
</div>

<!-- Delete Single User -->
<div class="modal fade" id="SelectedDeleteModal" tabindex="-1" aria-labelledby="exampleModalCenteredLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenteredLabel">Delete Comments!</h5>
            </div>
            <div class="modal-body">Are you sure you want to delete the selected users comments?</div>
            <div class="modal-footer">
                <button class="btn btn-outline-dark me-2" type="button" data-bs-dismiss="modal">Nope</button>
                <button class="btn btn-outline-danger" type="button" onclick="DeleteSelected()">Yes Take Down</button>
            </div>
        </div>
    </div>
</div>

<script>
$('.check-all').on('click', function(event) {
    $('input:checkbox').not(this).prop('checked', this.checked);
});
$('.delete-checkbox, .check-all').change(function(event) {
    $('.delete-selected').attr('disabled', false);
    $('.delete-selected').find('span').text(' (' + $('.delete-checkbox:checked').length + ')');
});
$('.delete-selected').on('click', function(event) {
    event.preventDefault();
    $('#SelectedDeleteModal').modal('show');
});
function DeleteSelected() {
    data = new Array();
    $('td input:checked').parents('tr').each(function () {
        data.push($(this).attr('data_selected'));
    });
    $('.delete-selected').attr('disabled', true);
    $('.delete-selected').text('Please wait...');
    $.post(cpanel_ajax_url('delete-multi-comments'), {ids: data}, function () {
        $.each( data, function( index, value ){
            $("#list-"+value).remove();
        });
        $('#SelectedDeleteModal').modal('hide');
        let notify_success201 = {status: 'success',title: 'Post Comments',text: 'Comments deleted Successfully!',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
        new Notify({ ...notify_success201 });
        $('#redirect_link').attr('href', "<?php echo cpanel('comments-reply'); ?>");
        $('#redirect_link').attr('data-ajax', "?path=comments-reply");
        $('#redirect_link').click();
        $('.delete-selected').text('Take Down');
    });
}
$('#Search').on('click', function(event) {
    event.preventDefault();
    var item = $('#query');
    var text = item.val();

    const accinput = $('#user_type');
    const AccType = accinput.val();
    $('#redirect_link').attr('href', "<?php echo cpanel('comments-reply').$rang_link_href; ?>query="+text);
    $('#redirect_link').attr('data-ajax', "?path=comments-reply<?php echo($search_link); ?>query="+text);
    $('#redirect_link').click();
});

function DeleteComment(id,type = 'show'){
  if (id && id > 0) {
    if (type == 'hide') {
      $('#DeleteModal').find('.btn-outline-danger').attr('onclick', "DeleteComment('"+id+"')");
      $('#DeleteModal').modal('show');
      return false;
    }
    $("#list-"+id).slideUp(function(){
      $(this).remove();
    });
    $("#DeleteModal").modal("hide");
    $.ajax({
      url: cpanel_ajax_url('delete-comments'),
      type: 'POST',
      dataType: 'json',
      data: {id:id}
    });
    $('#redirect_link').attr('href', "<?php echo cpanel('comments-reply'); ?>");
    $('#redirect_link').attr('data-ajax', "?path=comments-reply");
    $('#redirect_link').click();
    let notify_success201 = {status: 'success',title: 'Post Comments',text: 'Comments deleted Successfully!',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
    new Notify({ ...notify_success201 });
  }
}

//YEARLY COMMENTS DATA CHART
function yearly_comments() {
    if ($('#yearly-comments-stats').length) {
        var options = {
            chart: {
                type: 'bar',
                fontFamily: "Viga",
                offsetX: -26,
                stacked: false,
                height: 275,
                width: '100%',
                toolbar: {
                    show: false
                }
            },
            dataLabels: {
                enabled: false
            },
        series: [{
        name: 'Post Comments',
        data: [<?php echo $comments_yearly_data; ?>]
        },
        {
        name: 'Comments Replies',
        data: [<?php echo $yearly_comments_replies; ?>]
        },
        {
        name: 'Comments Liked',
        data: [<?php echo $yearly_comments_liked; ?>]
        },
        {
        name: 'Replies Liked',
        data: [<?php echo $y_coms_rep_liked; ?>]
        }],
            plotOptions: {
                bar: {
                    horizontal: false,
                    columnWidth: '60%',
                    endingShape: 'flat'
                },
            },
            colors: ['<?php echo ($mode == 'night' ? '#6a6a6a' : '#00a8f6'); ?>', '<?php echo ($mode == 'night' ? '#6a6a6a' : '#fd7e14'); ?>', '<?php echo ($mode == 'night' ? '#6a6a6a' : '#ff3380'); ?>', '<?php echo ($mode == 'night' ? '#6a6a6a' : '#ff0000'); ?>'],
            xaxis: {
                <?php if ($chart_type == 'This Year') { ?>
                    categories: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October','November','December']
                <?php } ?>
            },
            tooltip: {
                y: {
                    formatter: function (val) {
                        return val
                    }
                }
            }
        };

        var chart = new ApexCharts(
            document.querySelector("#yearly-comments-stats"),
            options
        );
        chart.render();
    }
}

yearly_comments();

tippy('.lastpage', {
	arrow: false,
	content: 'Last Page',
});
tippy('.nextpage', {
	arrow: false,
	content: 'Next Page',
});
tippy('.previouspage', {
	arrow: false,
	content: 'Previous Page',
});
tippy('.firstpage', {
	arrow: false,
	content: 'First Page',
});

tippy('#verify', {
	arrow: false,
	content: 'Verified',
});
tippy('#partner', {
	arrow: false,
	content: 'Partner',
});

</script>