<?php 
define('T_CONFIG', 'config');
define('T_LANGS', 'langs');
define('T_SESSIONS', 'sessions');
define('T_USERS', 'users');
define('T_MEDIA', 'media_files');
define('T_POSTS', 'posts');
define('T_POST_COMMENTS', 'post_comments');
define('T_CONNECTIV', 'connectivities');
define('T_MESSAGES', 'messages');
define('T_STORY', 'story');
define('T_STORY_VIEWS', 'story_views');
define('T_NOTIF', 'notifications');
define('T_POST_LIKES', 'post_likes');
define('T_CHATS', 'chats');
define('T_SAVED_POSTS', 'saved_posts');
define('T_POST_REPORTS','post_reports');
define('T_USER_REPORTS','user_reports');
define('T_PROF_BLOCKS','blocks');
define('T_HTAGS','hashtags');
define('T_VERIFY','verification');
define('T_BLACKLIST','blacklist');
define('T_ACTIVITIES','activities');
define('T_COMMENTS_LIKES','comments_likes');
define('T_COMMENTS_REPLY','comments_reply');
define('T_COMMENTS_REPLY_LIKES','comments_reply_likes');
define('T_PAYMENTS', 'payments');
define('T_ADS', 'campaigns');
define('T_TRANSACTIONS', 'transactions');
define('T_BANNED_IPS', 'banned_ip');
define('T_SUBSCRIBERS', 'subscribers');
define('T_POINT_SYSTEM', 'point_system');