<tr id="VerificationID_<?php echo $context['verification']->id?>" data_selected="<?php echo $context['verification']->id?>">
   <td>
      <div class="form-check">
         <input class="form-check-input delete-checkbox" id="check-data-<?php echo $context['verification']->id?>" type="checkbox" value="" />
         <label class="form-check-label" for="check-data-<?php echo $context['verification']->id?>"></label>
      </div>
   </td>
   <td><?php echo $context['verification']->id?> </td>
   <td>
      <a href="<?php echo $context['verification']->request_from->url; ?>" class="text-decoration-none" target="_blank">
         <img src="<?php echo $context['verification']->request_from->avatar?>" class="rounded-circle" alt="..." style="height: 2rem;weight:2rem;">
      </a>
      &nbsp; <?php echo $context['verification']->request_from->name; ?>
   </td>
   <td><?php echo time2str($context['verification']->request_from->time);?></td>
   <td><?php echo $context['verification']->request_from->gender; ?></td>
   <td><button type="button" data-toggle="modal" class="btn btn-outline-primary toggle-verification-request" data-target="#review-verif-request-info-<?php echo $context['verification']->id; ?>">Show Data</button></td>
   <td>
      <button data-id="<?php echo $context['verification']->request_from->user_id ?>,<?php echo $context['verification']->id?>" onclick="ApproveVerify(<?php echo $context['verification']->request_from->user_id ?>,<?php echo $context['verification']->id?>,'','hide')" type="button" class="btn btn-outline-success">Verify</button>&nbsp;&nbsp;
      <button data-id="<?php echo $context['verification']->id?>" onclick="DeclineVerification(<?php echo $context['verification']->id?>,'hide')" type="button" class="btn btn-outline-danger">Decline</button>
   </td>
</tr>
<div class="modal fade z-index-modal infocheck" id="review-verif-request-info-<?php echo $context['verification']->id; ?>" tabindex="1" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Verification Infomation</h5>
         </div>
         <div class="modal-body">
            <div class="row">
               <div class="col-md-6">
                  <a href="<?php echo media($context['verification']->passport); ?>" class="image-popup-gallery-item-<?php echo $context['verification']->id; ?>">
                     <div class="image-hover">
                        <img src="<?php echo media($context['verification']->passport); ?>" class="rounded" alt="image" style="width: 100%;min-height: 200px;max-height: 200px; ">
                        <div class="image-hover-body rounded">
                           <div><h4 class="mb-2">Passport</h4></div>
                        </div>
                     </div>
                  </a>
               </div>
               <div class="col-md-6">
                  <a href="<?php echo media($context['verification']->photo); ?>" class="image-popup-gallery-item-<?php echo $context['verification']->id; ?>">
                     <div class="image-hover">
                        <img src="<?php echo media($context['verification']->photo); ?>" class="rounded" alt="image" style="width: 100%;min-height: 200px;max-height: 200px;">
                        <div class="image-hover-body rounded">
                           <div><h4 class="mb-2">Photo</h4></div>
                        </div>
                     </div>
                  </a>
               </div>
            </div>
            <br>
            <p class="mb-1"><span class="badge bg-primary">Name</span></p>
            <p><?php echo $context['verification']->name; ?></p>
            <p class="mb-1"><span class="badge bg-info">Message</span></p>
            <p><?php echo $context['verification']->message; ?></p>
         </div>
         <div class="modal-footer">
            <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Close</button>
         </div>
      </div>
   </div>
</div>

<style>
.image-hover {position: relative;}
.image-hover .image-hover-body {display: flex;align-items: flex-end;opacity: 0;visibility: hidden;position: absolute;right: 0;left: 0;top: 0;bottom: 0;background: rgba(0, 0, 0, 0.5);transition: all 0.3s;color: white;padding: 20px 30px;}
.image-hover:hover .image-hover-body {opacity: 1;visibility: visible;}
.image-hover .image-hover-body h4{color: #fff;}
</style>
<script type="text/javascript">
   $(document).ready(function() {
      $('#review-verif-request-info-<?php echo $context['verification']->id; ?>').modal('hide');
      $('.image-popup-gallery-item-<?php echo $context['verification']->id; ?>').magnificPopup({
           type: 'image',
           gallery: {
               enabled: false
           },
           zoom: {
               enabled: true,
               duration: 400,
               easing: 'ease-in-out',
               opener: function(openerElement) {
                   return openerElement.is('img') ? openerElement : openerElement.find('img');
               }
           }
       });
   });
</script>