<?php  
$tot_users = $cpanel->totalUsers();
$tot_posts = $cpanel->totalPosts();
$onl_users = $cpanel->onlineUsers();
$tot_comms = $cpanel->totalComments();
$tot_mssgs = $cpanel->totalMessages();
$tot_vids  = $cpanel->totalVideos();
$tot_imgs  = $cpanel->totalPhotos();
$tot_liks  = $cpanel->totalLikes();
$tot_tiles  = $cpanel->totalTiles();

$this_start = strtotime("1 January ".date('Y')." 12:00am");
$this_end = strtotime("31 December ".date('Y')." 11:59pm");
$array = array('01' => 0 ,'02' => 0 ,'03' => 0 ,'04' => 0 ,'05' => 0 ,'06' => 0 ,'07' => 0 ,'08' => 0 ,'09' => 0 ,'10' => 0 ,'11' => 0 ,'12' => 0);
$code = 'm';
$main_range = 'This Year';
$title = "Yearly";
if (!empty($_GET['range']) && in_array($_GET['range'], array('Today','Yesterday','This Week','This Month','Last Month'))) {
    if ($_GET['range'] == 'Today' || $_GET['range'] == 'Yesterday') {
        $array = array('00' => 0 ,'01' => 0 ,'02' => 0 ,'03' => 0 ,'04' => 0 ,'05' => 0 ,'06' => 0 ,'07' => 0 ,'08' => 0 ,'09' => 0 ,'10' => 0 ,'11' => 0 ,'12' => 0 ,'13' => 0 ,'14' => 0 ,'15' => 0 ,'16' => 0 ,'17' => 0 ,'18' => 0 ,'19' => 0 ,'20' => 0 ,'21' => 0 ,'22' => 0 ,'23' => 0);
        $this_start = strtotime(date('M')." ".date('d').", ".date('Y')." 12:00am");
        $this_end = strtotime(date('M')." ".date('d').", ".date('Y')." 11:59pm");
        if ($_GET['range'] == 'Yesterday') {
            $this_start = strtotime(date('M')." ".date('d',strtotime("-1 days")).", ".date('Y')." 12:00am");
            $this_end = strtotime(date('M')." ".date('d',strtotime("-1 days")).", ".date('Y')." 11:59pm");
        }
        $code = 'H';
        $main_range = 'Today';
        $title = "Daily";
    }
    elseif ($_GET['range'] == 'This Week') {
        $time = strtotime(date('l').", ".date('M')." ".date('d').", ".date('Y'));

        if (date('l') == 'Saturday') {
            $this_start = strtotime(date('M')." ".date('d').", ".date('Y')." 12:00am");
        }
        else{
            $this_start = strtotime('last saturday, 12:00am', $time);
        }

        if (date('l') == 'Friday') {
            $this_end = strtotime(date('M')." ".date('d').", ".date('Y')." 11:59pm");
        }
        else{
            $this_end = strtotime('next Friday, 11:59pm', $time);
        }
        
        $array = array('Saturday' => 0 , 'Sunday' => 0 , 'Monday' => 0 , 'Tuesday' => 0 , 'Wednesday' => 0 , 'Thursday' => 0 , 'Friday' => 0);
        $code = 'l';
        $main_range = 'This Week';
        $title = "Weekly";
    }
    elseif ($_GET['range'] == 'This Month' ||$_GET['range'] == 'Last Month') {
        $this_start = strtotime("1 ".date('M')." ".date('Y')." 12:00am");
        $this_end = strtotime(cal_days_in_month(CAL_GREGORIAN, date('m'), date('Y'))." ".date('M')." ".date('Y')." 11:59pm");
        $array = array_fill(1, cal_days_in_month(CAL_GREGORIAN, date('m'), date('Y')),0);
        $month_days = cal_days_in_month(CAL_GREGORIAN, date('m'), date('Y'));
        if ($_GET['range'] == 'Last Month') {
            $this_start = strtotime("1 ".date('M',strtotime("-1 month"))." ".date('Y')." 12:00am");
            $this_end = strtotime(cal_days_in_month(CAL_GREGORIAN, date('m',strtotime("-1 month")), date('Y'))." ".date('M',strtotime("-1 month"))." ".date('Y')." 11:59pm");
            $array = array_fill(1, cal_days_in_month(CAL_GREGORIAN, date('m',strtotime("-1 month")), date('Y')),0);
            $month_days = cal_days_in_month(CAL_GREGORIAN, date('m',strtotime("-1 month")), date('Y'));
        }
        if (cal_days_in_month(CAL_GREGORIAN, date('m'), date('Y')) == 31) {
            $array = array('01' => 0 ,'02' => 0 ,'03' => 0 ,'04' => 0 ,'05' => 0 ,'06' => 0 ,'07' => 0 ,'08' => 0 ,'09' => 0 ,'10' => 0 ,'11' => 0 ,'12' => 0 ,'13' => 0 ,'14' => 0 ,'15' => 0 ,'16' => 0 ,'17' => 0 ,'18' => 0 ,'19' => 0 ,'20' => 0 ,'21' => 0 ,'22' => 0 ,'23' => 0,'24' => 0 ,'25' => 0 ,'26' => 0 ,'27' => 0 ,'28' => 0 ,'29' => 0 ,'30' => 0 ,'31' => 0);
        }elseif (cal_days_in_month(CAL_GREGORIAN, date('m'), date('Y')) == 30) {
            $array = array('01' => 0 ,'02' => 0 ,'03' => 0 ,'04' => 0 ,'05' => 0 ,'06' => 0 ,'07' => 0 ,'08' => 0 ,'09' => 0 ,'10' => 0 ,'11' => 0 ,'12' => 0 ,'13' => 0 ,'14' => 0 ,'15' => 0 ,'16' => 0 ,'17' => 0 ,'18' => 0 ,'19' => 0 ,'20' => 0 ,'21' => 0 ,'22' => 0 ,'23' => 0,'24' => 0 ,'25' => 0 ,'26' => 0 ,'27' => 0 ,'28' => 0 ,'29' => 0 ,'30' => 0);
        }elseif (cal_days_in_month(CAL_GREGORIAN, date('m'), date('Y')) == 29) {
            $array = array('01' => 0 ,'02' => 0 ,'03' => 0 ,'04' => 0 ,'05' => 0 ,'06' => 0 ,'07' => 0 ,'08' => 0 ,'09' => 0 ,'10' => 0 ,'11' => 0 ,'12' => 0 ,'13' => 0 ,'14' => 0 ,'15' => 0 ,'16' => 0 ,'17' => 0 ,'18' => 0 ,'19' => 0 ,'20' => 0 ,'21' => 0 ,'22' => 0 ,'23' => 0,'24' => 0 ,'25' => 0 ,'26' => 0 ,'27' => 0 ,'28' => 0 ,'29' => 0);
        }elseif (cal_days_in_month(CAL_GREGORIAN, date('m'), date('Y')) == 28) {
            $array = array('01' => 0 ,'02' => 0 ,'03' => 0 ,'04' => 0 ,'05' => 0 ,'06' => 0 ,'07' => 0 ,'08' => 0 ,'09' => 0 ,'10' => 0 ,'11' => 0 ,'12' => 0 ,'13' => 0 ,'14' => 0 ,'15' => 0 ,'16' => 0 ,'17' => 0 ,'18' => 0 ,'19' => 0 ,'20' => 0 ,'21' => 0 ,'22' => 0 ,'23' => 0,'24' => 0 ,'25' => 0 ,'26' => 0 ,'27' => 0 ,'28' => 0);
        }
        $code = 'd';
        $main_range = 'This Month';
        $title = "Monthly";
    }
}
$start = '';
$end = '';
$first_code = '';
$second_code = '';
if (!empty($_GET['range']) && !in_array($_GET['range'], array('Today','Yesterday','This Week','This Month','Last Month','This Year'))) {
    $arr = explode('-', $_GET['range']);
    if (preg_match('~(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d~m', $arr[0]) && preg_match('~(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d~m', $arr[1])) {
        $start = $cpanel::secure($arr[0]);
        $end = $cpanel::secure($arr[1]);
        $this_start = strtotime($start);
        $this_end = strtotime($end);
        $month_days = cal_days_in_month(CAL_GREGORIAN, date('m',strtotime($start)), date('Y',strtotime($start)));
        $diff = abs(strtotime($end) - strtotime($start));
        $years = floor($diff / (365*60*60*24));
        $months = floor(($diff - $years * 365*60*60*24) / (30*60*60*24));
        $days = floor(($diff - $years * 365*60*60*24 - $months*30*60*60*24)/ (60*60*24));
        if ($years >= 1) {
            $array = array();
            for ($i=date('Y',strtotime($start)); $i <= date('Y',strtotime($end)); $i++) { 
                $array["'".$i."'"] = 0;
            }
            $main_range = 'Custom';
            $code = 'Y';
            $title = "Yearly";
        }
        elseif ($months >= 1) {
            $array = array('01' => 0 ,'02' => 0 ,'03' => 0 ,'04' => 0 ,'05' => 0 ,'06' => 0 ,'07' => 0 ,'08' => 0 ,'09' => 0 ,'10' => 0 ,'11' => 0 ,'12' => 0);
            $code = 'm';
            $main_range = 'This Year';
            $title = "Monthly";
            if (date('Y',strtotime($start)) == date('Y',strtotime($end))) {
                $array = array();
                for ($i=date('m',strtotime($start)); $i <= date('m',strtotime($end)); $i++) { 
                    $array["'".(int)$i."'"] = 0;
                }
                $code = 'm';
                $main_range = 'Custom';
            }
            else{
                $month = cal_days_in_month(CAL_GREGORIAN, date('m',strtotime($start)), date('Y',strtotime($start)));
                $array = array();
                for ($i=(int)date('m',strtotime($start)); $i <= 12; $i++) { 
                    $array["'".(int)$i.'-'.date('Y',strtotime($start))."'"] = 0;
                }
                for ($i=1; $i <= (int)date('m',strtotime($end)); $i++) { 
                    $array["'".(int)$i.'-'.date('Y',strtotime($end))."'"] = 0;
                }
                $first_code = 'm';
                $second_code = 'Y';
                $main_range = 'Custom';
            }
        }
        elseif ($days > 7) {
            if (date('m',strtotime($start)) == date('m',strtotime($end))) {
                $array = array();
                for ($i=date('d',strtotime($start)); $i <= date('d',strtotime($end)); $i++) { 
                    $array["'".(int)$i."'"] = 0;
                }
                $code = 'd';
                $main_range = 'Custom';
            }
            else{
                $month = cal_days_in_month(CAL_GREGORIAN, date('m',strtotime($start)), date('Y',strtotime($start)));
                $array = array();
                for ($i=(int)date('d',strtotime($start)); $i <= $month; $i++) { 
                    $array["'".(int)$i.'-'.date('m',strtotime($start))."'"] = 0;
                }
                for ($i=1; $i <= (int)date('d',strtotime($end)); $i++) { 
                    $array["'".(int)$i.'-'.date('m',strtotime($end))."'"] = 0;
                }
                $first_code = 'd';
                $second_code = 'm';
                $main_range = 'Custom';
            }
            $title = "Daily";
        }
        elseif ($days >= 1 && $days < 8) {
            $title = "Daily";
            $code = 'l';
            $array = array('Saturday' => 0 , 'Sunday' => 0 , 'Monday' => 0 , 'Tuesday' => 0 , 'Wednesday' => 0 , 'Thursday' => 0 , 'Friday' => 0);
            if (date('m',strtotime($start)) == date('m',strtotime($end))) {
                $array = array();
                for ($i=date('d',strtotime($start)); $i <= date('d',strtotime($end)); $i++) { 
                    $array["'".(int)$i."'"] = 0;
                }
                $code = 'd';
                $main_range = 'Custom';
            }
            else{
                $month = cal_days_in_month(CAL_GREGORIAN, date('m',strtotime($start)), date('Y',strtotime($start)));
                $array = array();
                for ($i=(int)date('d',strtotime($start)); $i <= $month; $i++) { 
                    $array["'".(int)$i.'-'.date('m',strtotime($start))."'"] = 0;
                }
                for ($i=1; $i <= (int)date('d',strtotime($end)); $i++) { 
                    $array["'".(int)$i.'-'.date('m',strtotime($end))."'"] = 0;
                }
                $first_code = 'd';
                $second_code = 'm';
                $main_range = 'Custom';
            }
        }
    }
}

// Users Chart
$users_array = $array;
$users = $cpanel::$db->where('time',$this_start,'>=')->where('time',$this_end,'<=')->get(T_USERS,null,array('time'));
foreach ($users as $key => $value) {
    $day = date($code,$value->time);
    if ($main_range == 'Custom' && !empty($first_code) && !empty($second_code)) {
        $day = "'".(int)date($first_code,$value->time).'-'.(int)date($second_code,$value->time)."'";
    }
    elseif ($main_range == 'Custom') {
        $day = "'".(int)date($code,$value->time)."'";
    }
    if (in_array($day, array_keys($users_array))) {
        $users_array[$day] += 1; 
    }
}
$u_array = implode(', ', $users_array);
$users = array();
$users_array = array();

// Posts Chart
$posts_array = $array;
$posts = $cpanel::$db->where('time',$this_start,'>=')->where('time',$this_end,'<=')->get(T_POSTS,null,array('time'));
foreach ($posts as $key => $value) {
    $day = date($code,$value->time);
    if ($main_range == 'Custom' && !empty($first_code) && !empty($second_code)) {
        $day = "'".(int)date($first_code,$value->time).'-'.(int)date($second_code,$value->time)."'";
    }
    elseif ($main_range == 'Custom') {
        $day = "'".(int)date($code,$value->time)."'";
    }
    if (in_array($day, array_keys($posts_array))) {
        $posts_array[$day] += 1; 
    }
}
$p_array = implode(', ', $posts_array);
$posts = array();
$posts_array = array();

// Messages chart
$messages_array = $array;
$messages = $cpanel::$db->where('time',$this_start,'>=')->where('time',$this_end,'<=')->get(T_MESSAGES,null,array('time'));
foreach ($messages as $key => $value) {
    $day = date($code,$value->time);
    if ($main_range == 'Custom' && !empty($first_code) && !empty($second_code)) {
        $day = "'".(int)date($first_code,$value->time).'-'.(int)date($second_code,$value->time)."'";
    }
    elseif ($main_range == 'Custom') {
        $day = "'".(int)date($code,$value->time)."'";
    }
    if (in_array($day, array_keys($messages_array))) {
        $messages_array[$day] += 1; 
    }
}
$m_array = implode(', ', $messages_array);
$messages = array();
$messages_array = array();

// Posts Likes chart
$posts_likes_array = $array;
$posts_likes = $cpanel::$db->where('time',$this_start,'>=')->where('time',$this_end,'<=')->get(T_POST_LIKES,null,array('time'));
foreach ($posts_likes as $key => $value) {
    $day = date($code,$value->time);
    if ($main_range == 'Custom' && !empty($first_code) && !empty($second_code)) {
        $day = "'".(int)date($first_code,$value->time).'-'.(int)date($second_code,$value->time)."'";
    }
    elseif ($main_range == 'Custom') {
        $day = "'".(int)date($code,$value->time)."'";
    }
    if (in_array($day, array_keys($posts_likes_array))) {
        $posts_likes_array[$day] += 1; 
    }
}
$pl_array = implode(', ', $posts_likes_array);
$posts_likes = array();
$posts_likes_array = array();


// Post comments based on per week
$comments_charts = array('This Week');
$chart = 'This Week';
if (!empty($_GET['chart']) && in_array($_GET['chart'], $comments_charts)) {
	$chart = $_GET['chart'];
}

if ($chart == 'This Week') {
    $chart_type = 'This Week';
    $time = strtotime(date('l').", ".date('M')." ".date('d').", ".date('Y'));
    if (date('l') == 'Saturday') {
        $start_week = strtotime(date('M')." ".date('d').", ".date('Y')." 12:00am");
    }
    else{
        $start_week = strtotime('last saturday, 12:00am', $time);
    }

    if (date('l') == 'Friday') {
        $end_the_week = strtotime(date('M')." ".date('d').", ".date('Y')." 11:59pm");
    }
    else{
        $end_the_week = strtotime('next Friday, 11:59pm', $time);
    }
    $array_eye =  array('Saturday' => 0 , 'Sunday' => 0 , 'Monday' => 0 , 'Tuesday' => 0 , 'Wednesday' => 0 , 'Thursday' => 0 , 'Friday' => 0);
    $post_comments_array = $array_eye;

    $post_comments = $cpanel::$db->where('time',$start_week,'>=')->where('time',$end_the_week,'<=')->get(T_POST_COMMENTS,null,array('time'));
    foreach ($post_comments as $key => $value) {
        $hour = date('l',$value->time);
		if (in_array($hour, array_keys($post_comments_array))) {
			$post_comments_array[$hour] += 1; 
		}
    }

    $comms_array = implode(', ', $post_comments_array);
    $post_comments = array();
    $post_comments_array = array();
}

// Messages sent based on this week
$messages_charts = array('This Week');
$chart = 'This Week';
if (!empty($_GET['chart']) && in_array($_GET['chart'], $messages_charts)) {
	$chart = $_GET['chart'];
}

if ($chart == 'This Week') {
    $chart_type = 'This Week';
    $time = strtotime(date('l').", ".date('M')." ".date('d').", ".date('Y'));
    if (date('l') == 'Saturday') {
        $start_week = strtotime(date('M')." ".date('d').", ".date('Y')." 12:00am");
    }
    else{
        $start_week = strtotime('last saturday, 12:00am', $time);
    }

    if (date('l') == 'Friday') {
        $end_the_week = strtotime(date('M')." ".date('d').", ".date('Y')." 11:59pm");
    }
    else{
        $end_the_week = strtotime('next Friday, 11:59pm', $time);
    }
    $array_eye =  array('Saturday' => 0 , 'Sunday' => 0 , 'Monday' => 0 , 'Tuesday' => 0 , 'Wednesday' => 0 , 'Thursday' => 0 , 'Friday' => 0);
    $messages_sent_array = $array_eye;

    $messages_sent = $cpanel::$db->where('time',$start_week,'>=')->where('time',$end_the_week,'<=')->get(T_MESSAGES,null,array('time'));
    foreach ($messages_sent as $key => $value) {
        $hour = date('l',$value->time);
		if (in_array($hour, array_keys($messages_sent_array))) {
			$messages_sent_array[$hour] += 1; 
		}
    }

    $msg_array = implode(', ', $messages_sent_array);
    $messages_sent = array();
    $messages_sent_array = array();
}

// New members based on this week
$members_charts = array('This Week');
$chart = 'This Week';
if (!empty($_GET['chart']) && in_array($_GET['chart'], $members_charts)) {
	$chart = $_GET['chart'];
}

if ($chart == 'This Week') {
    $chart_type = 'This Week';
    $time = strtotime(date('l').", ".date('M')." ".date('d').", ".date('Y'));
    if (date('l') == 'Saturday') {
        $start_week = strtotime(date('M')." ".date('d').", ".date('Y')." 12:00am");
    }
    else{
        $start_week = strtotime('last saturday, 12:00am', $time);
    }

    if (date('l') == 'Friday') {
        $end_the_week = strtotime(date('M')." ".date('d').", ".date('Y')." 11:59pm");
    }
    else{
        $end_the_week = strtotime('next Friday, 11:59pm', $time);
    }
    $array_eye =  array('Saturday' => 0 , 'Sunday' => 0 , 'Monday' => 0 , 'Tuesday' => 0 , 'Wednesday' => 0 , 'Thursday' => 0 , 'Friday' => 0);
    $new_members_array = $array_eye;

    $new_members = $cpanel::$db->where('time',$start_week,'>=')->where('time',$end_the_week,'<=')->get(T_USERS,null,array('time'));
    foreach ($new_members as $key => $value) {
        $hour = date('l',$value->time);
		if (in_array($hour, array_keys($new_members_array))) {
			$new_members_array[$hour] += 1; 
		}
    }

    $members_array = implode(', ', $new_members_array);
    $new_members = array();
    $new_members_array = array();
}

// New members based on this week
$members_charts = array('This Week');
$chart = 'This Week';
if (!empty($_GET['chart']) && in_array($_GET['chart'], $members_charts)) {
	$chart = $_GET['chart'];
}

if ($chart == 'This Week') {
    $chart_type = 'This Week';
    $time = strtotime(date('l').", ".date('M')." ".date('d').", ".date('Y'));
    if (date('l') == 'Saturday') {
        $start_week = strtotime(date('M')." ".date('d').", ".date('Y')." 12:00am");
    }
    else{
        $start_week = strtotime('last saturday, 12:00am', $time);
    }

    if (date('l') == 'Friday') {
        $end_the_week = strtotime(date('M')." ".date('d').", ".date('Y')." 11:59pm");
    }
    else{
        $end_the_week = strtotime('next Friday, 11:59pm', $time);
    }
    $array_eye =  array('Saturday' => 0 , 'Sunday' => 0 , 'Monday' => 0 , 'Tuesday' => 0 , 'Wednesday' => 0 , 'Thursday' => 0 , 'Friday' => 0);
    $post_likes_array_array = $array_eye;

    $is_posts_likes = $cpanel::$db->where('time',$start_week,'>=')->where('time',$end_the_week,'<=')->get(T_POST_LIKES,null,array('time'));
    foreach ($is_posts_likes as $key => $value) {
        $hour = date('l',$value->time);
		if (in_array($hour, array_keys($post_likes_array_array))) {
			$post_likes_array_array[$hour] += 1; 
		}
    }

    $post_likes_array = implode(', ', $post_likes_array_array);
    $is_posts_likes = array();
    $post_likes_array_array = array();
}

$mode = 'day';
if (!empty($_COOKIE['mode']) && $_COOKIE['mode'] == 'night') {
    $mode = 'night';
}

?>
<div class="row justify-content-between align-items-center mb-5">
    <div class="col flex-shrink-0 mb-5 mb-md-0">
        <h1 class="display-4 mb-0">Dashboard</h1>
        <div class="text-muted">Statistics &amp; dashboard overview</div>
    </div>
</div>
<!-- Colored status cards-->
<div class="row gx-5">
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-dark border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $tot_users; ?></div>
                        <div class="card-text">Total Members</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/people.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-indigo border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $tot_comms; ?></div>
                        <div class="card-text">Total Comments</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/message_comments.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-warning border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $tot_posts; ?></div>
                        <div class="card-text">Total Posts</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/social-media.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-secondary border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $tot_imgs; ?></div>
                        <div class="card-text">Total Images</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/images.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-primary border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $tot_mssgs; ?></div>
                        <div class="card-text">Total Messages</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/message.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-info border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $tot_vids; ?></div>
                        <div class="card-text">Total Videos</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/movie.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-danger border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $tot_liks; ?></div>
                        <div class="card-text">Total Post Likes</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/heart.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-info border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $tot_tiles; ?></div>
                        <div class="card-text">Total Tiles</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/video-camera.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>

</div>
<div class="row gx-5">
    <!-- Revenue breakdown chart example-->
    <div class="col-lg-12 mb-5">
        <div class="card card-raised h-100 border-start border-<?php echo $me['dash_color']; ?> border-4">
            <div class="card-header bg-white px-4">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="me-4">
                        <h2 class="card-title mb-0">Community Statistics</h2>
                        <div class="card-subtitle"><?php echo $config['site_name']; ?> overall statistics based on <?php if (!empty($_GET['range']) && in_array($_GET['range'], array('Today','Yesterday','This Week','This Month','Last Month','This Year'))) {
                            echo $_GET['range'];
                            }else if (!empty($start) && !empty($end)){
                                echo $_GET['range'];
                            }else{
                                echo 'This Year';
                            } ?>
                        </div>
                    </div>
                    <div class="d-flex gap-2 me-n2">
                        <div id="dashboard-daterangepicker" class="btn btn-outline-dark">
                            <?php 
                            if (!empty($_GET['range']) && in_array($_GET['range'], array('Today','Yesterday','This Week','This Month','Last Month','This Year'))) {
                                    echo $_GET['range'];
                            }else if (!empty($start) && !empty($end)){
                                echo $_GET['range'];
                            }else{
                                echo 'This Year';
                            } ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body p-4">
                <div id="chart-container" style="min-width: 100%; height: 200px;"></div>
            </div>
        </div>
    </div>
</div>
<div class="row gx-5">
    <!-- Messages Card-->
    <div class="col-xl-6 mb-5">
        <div class="card card-raised h-100 border-start border-info border-4">
            <div class="card-header bg-white px-4">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="me-4">
                        <h2 class="card-title mb-0">Messages Chart</h2>
                        <div class="card-subtitle">Messages sent statistics based on this week</div>
                    </div>
                    <div class="d-flex gap-2 me-n2">
                        <img src="<?php echo cpanel('si/img/icons/message-love.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                    </div>
                </div>
            </div>
            <div class="card-body p-4">
                <div id="messages-chart"  style="min-width: 100%;"></div>
            </div>
        </div>
    </div>

    <!-- Comments Card-->
    <div class="col-xl-6 mb-5">
        <div class="card card-raised h-100 border-start border-secondary border-4">
            <div class="card-header bg-white px-4">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="me-4">
                            <h2 class="card-title mb-0">Comments Chart</h2>
                            <div class="card-subtitle">Post comments statistics based on this week
                            </div>
                        </div>
                        <div class="d-flex gap-2 me-n2">
                            <img src="<?php echo cpanel('si/img/icons/histogram.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                        </div>
                    </div>
                </div>
                <div class="card-body p-4">
                    <div id="comments-chart"  style="min-width: 100%;"></div>
                </div>
            </div>
        </div>

    <!-- New Members Card-->
    <div class="col-xl-6 mb-5">
        <div class="card card-raised h-100 border-start border-success border-4">
            <div class="card-header bg-white px-4">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="me-4">
                        <h2 class="card-title mb-0">Members Chart</h2>
                        <div class="card-subtitle">New members statistics based on this week</div>
                    </div>
                    <div class="d-flex gap-2 me-n2">
                        <img src="<?php echo cpanel('si/img/icons/people.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                    </div>
                </div>
            </div>
            <div class="card-body p-4">
                <div id="members-chart"  style="min-width: 100%;"></div>
            </div>
        </div>
    </div>

    <!-- Post Likes Card-->
    <div class="col-xl-6 mb-5">
        <div class="card card-raised h-100 border-start border-pink border-4">
            <div class="card-header bg-white px-4">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="me-4">
                        <h2 class="card-title mb-0">Likes Chart</h2>
                        <div class="card-subtitle">Post likes statistics based on this week</div>
                    </div>
                    <div class="d-flex gap-2 me-n2">
                        <img src="<?php echo cpanel('si/img/icons/give-heart.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                    </div>
                </div>
            </div>
            <div class="card-body p-4">
                <div id="post_likes-chart"  style="min-width: 100%;"></div>
            </div>
        </div>
    </div>


<style>
.daterangepicker .ranges li.active {background-color: var(--bs-dark);color: #fff;}
.daterangepicker .drp-buttons .btn {background-color: var(--bs-dark);color: #fff;}
.daterangepicker td.active,
.daterangepicker td.active:hover {background-color: var(--bs-dark);border-color: transparent;color: #fff}
</style>
<script>
// MAIN CHART
    jQuery(document).ready(function($) {
        var range = { "Today": [moment() , moment()], 
            "Yesterday": [moment().subtract(1, 'days') , moment().subtract(1, 'days')], 
            "This_Week": [moment().subtract(6, 'days') , moment()],
            "This_Month": [moment().startOf('month') , moment().endOf('month')],
            "Last_Month": [moment().subtract(1, 'month').startOf('month') , moment().subtract(1, 'month').endOf('month')],
            "This_Year": [moment().subtract(1, 'year').startOf('year') , moment().subtract(1, 'year').endOf('year')]}; 
        <?php 
        if (!empty($_GET['range']) && in_array($_GET['range'], array('Today','Yesterday','This Week','This Month','Last Month','This Year'))) { 
            if ($_GET['range'] == 'Today') { ?>
                var start = range.Today[0];
                var end = range.Today[1];
            <?php }elseif ($_GET['range'] == 'Yesterday') { ?>
                var start = range.Yesterday[0];
                var end = range.Yesterday[1];
            <?php }elseif ($_GET['range'] == 'This Week') { ?>
                var start = range.This_Week[0];
                var end = range.This_Week[1];
            <?php }elseif ($_GET['range'] == 'This Month') { ?>
                var start = range.This_Month[0];
                var end = range.This_Month[1];
            <?php }elseif ($_GET['range'] == 'Last Month') { ?>
                var start = range.Last_Month[0];
                var end = range.Last_Month[1];
            <?php }elseif ($_GET['range'] == 'This Year') { ?>
                var start = range.This_Year[0];
                var end = range.This_Year[1];
            <?php } ?>
        <?php } elseif (!empty($_GET['range']) && !empty($start) && !empty($end)) { ?>
            var start = "<?php echo($start) ?>";
            var end = "<?php echo($end) ?>";
        <?php } else{ ?>
            var start = range.This_Year[0];
            var end = range.This_Year[1];
        <?php } ?>

        function cb(start, end) {
            //$('#dashboard-daterangepicker span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        }
        $('#dashboard-daterangepicker').daterangepicker({
            startDate: start,
            endDate: end,
            opens: $('body').hasClass('rtl') ? 'right' : 'left',
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'This Week': [moment().subtract(6, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                'This Year': [moment().subtract(1, 'year').startOf('year'), moment().subtract(1, 'year').endOf('year')],
            }
        }, cb);
        cb(start, end);
        $('#comments-daterangepicker').daterangepicker({
            startDate: start,
            endDate: end,
            opens: $('body').hasClass('rtl') ? 'right' : 'left',
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'This Week': [moment().subtract(6, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                'This Year': [moment().subtract(1, 'year').startOf('year'), moment().subtract(1, 'year').endOf('year')],
            }
        }, cb);
        cb(start, end);
        $(document).on('click', '.ranges ul li', function(event) {
            event.preventDefault();
            
            if ($(this).attr('data-range-key') != 'Custom Range') {
                $(document).off('click', '.ranges ul li');
                $('#redirect_link').attr('href', "<?php echo cpanel('dashboard'); ?>?range="+$(this).attr('data-range-key'));
                $('#redirect_link').attr('data-ajax', "?path=dashboard//range="+$(this).attr('data-range-key'));
                $('#redirect_link').click();
            }
        });
        $(document).on('click', '.applyBtn', function(event) {
            event.preventDefault();
            $(document).off('click', '.applyBtn');
            $('#redirect_link').attr('href', "<?php echo cpanel('dashboard'); ?>?range="+$(this).parent('.drp-buttons').find('.drp-selected').html());
            $('#redirect_link').attr('data-ajax', "?path=dashboard//range="+$(this).parent('.drp-buttons').find('.drp-selected').html());
            $('#redirect_link').click();
        });
    var rgbToHex = function (rgb) {
        var hex = Number(rgb).toString(16);
        if (hex.length < 2) {
            hex = "0" + hex;
        }
        return hex;
    };

    var fullColorHex = function (r, g, b) {
        var red = rgbToHex(r);
        var green = rgbToHex(g);
        var blue = rgbToHex(b);
        return red + green + blue;
    };

    var colors = {
        primary: $('.colors .bg-primary').css('background-color'),
        primaryLight: $('.colors .bg-primary-bright').css('background-color'),
        secondary: $('.colors .bg-secondary').css('background-color'),
        secondaryLight: $('.colors .bg-secondary-bright').css('background-color'),
        info: $('.colors .bg-info').css('background-color'),
        infoLight: $('.colors .bg-info-bright').css('background-color'),
        success: $('.colors .bg-success').css('background-color'),
        successLight: $('.colors .bg-success-bright').css('background-color'),
        danger: $('.colors .bg-danger').css('background-color'),
        dangerLight: $('.colors .bg-danger-bright').css('background-color'),
        warning: $('.colors .bg-warning').css('background-color'),
        warningLight: $('.colors .bg-warning-bright').css('background-color'),
    };
    //console.log(colors.primary[1]);
    colors.primary = '#' + fullColorHex(colors.primary[0], colors.primary[1], colors.primary[2]);
    colors.secondary = '#' + fullColorHex(colors.secondary[0], colors.secondary[1], colors.secondary[2]);
    colors.info = '#' + fullColorHex(colors.info[0], colors.info[1], colors.info[2]);
    colors.success = '#' + fullColorHex(colors.success[0], colors.success[1], colors.success[2]);
    colors.danger = '#' + fullColorHex(colors.danger[0], colors.danger[1], colors.danger[2]);
    colors.warning = '#' + fullColorHex(colors.warning[0], colors.warning[1], colors.warning[2]);
});

// USERS CHART
function users() {
    if ($('#chart-container').length) {
        var options = {
            chart: {
                type: 'bar',
                fontFamily: "Viga",
                offsetX: -26,
                stacked: false,
                height: 275,
                width: '100%',
                toolbar: {
                    show: false
                }
            },
            dataLabels: {
                enabled: false
            },
        series: [{
        name: 'Members',
        data: [<?php echo $u_array; ?>]
        },
        {
        name: 'Posts',
        data: [<?php echo $p_array; ?>]
        },
        {
        name: 'Messages',
        data: [<?php echo $m_array; ?>]
        },
        {
        name: 'Posts Likes',
        data: [<?php echo $pl_array; ?>]
        }],
            plotOptions: {
                bar: {
                    horizontal: false,
                    columnWidth: '48%',
                    endingShape: 'flat'
                },
            },
            colors: ['<?php echo ($mode == 'night' ? '#6a6a6a' : '#1b1b1b'); ?>', '<?php echo ($mode == 'night' ? '#6a6a6a' : '#ff0070'); ?>', '<?php echo ($mode == 'night' ? '#6a6a6a' : '#0d49fd'); ?>', '<?php echo ($mode == 'night' ? '#6a6a6a' : '#ea0b0b'); ?>'],
            xaxis: {
                <?php if ($main_range == 'Today' || $main_range == 'Yesterday') { ?>
                        categories: [
                            '00 AM',
                            '1 AM',
                            '2 AM',
                            '3 AM',
                            '4 AM',
                            '5 AM',
                            '6 AM',
                            '7 AM',
                            '8 AM',
                            '9 AM',
                            '10 AM',
                            '11 AM',
                            '12 PM',
                            '1 PM',
                            '2 PM',
                            '3 PM',
                            '4 PM',
                            '5 PM',
                            '6 PM',
                            '7 PM',
                            '8 PM',
                            '9 PM',
                            '10 PM',
                            '11 PM'
                        ]
                    <?php }elseif ($main_range == 'This Week') { ?>
                    categories: [
                        'Saturday',
                        'Sunday',
                        'Monday',
                        'Tuesday',
                        'Wednesday',
                        'Thursday',
                        'Friday'
                    ]
                    <?php }elseif ($main_range == 'This Month') { ?>
                        <?php if ($month_days == 31) { ?>
                            categories: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
                        <?php }elseif ($month_days == 30) { ?>
                            categories: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
                        <?php }elseif ($month_days == 29) { ?>
                            categories: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]
                        <?php }elseif ($month_days == 28) {  ?>
                            categories: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28]
                        <?php } ?>
                    <?php }elseif ($main_range == 'This Year') { ?>
                    categories: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October','November','December']
                    <?php }elseif ($main_range == 'Custom') {
                        echo "categories: [".implode(',',array_keys($array))."]";
                    } ?>
            },
            tooltip: {
                y: {
                    formatter: function (val) {
                        return val
                    }
                }
            }
        };

        var chart = new ApexCharts(
            document.querySelector("#chart-container"),
            options
        );
        chart.render();
    }
}

users();

//POST COMMENTS CHART
function comments() {
    if ($('#comments-chart').length) {
        var options = {
            chart: {
                type: 'bar',
                fontFamily: "Viga",
                offsetX: -26,
                stacked: false,
                height: 195,
                width: '100%',
                toolbar: {
                    show: false
                }
            },
            dataLabels: {
                enabled: false
            },
            series: [{
                name: 'Post Comments',
                data: [<?php echo $comms_array; ?>]
            }],
            plotOptions: {
                bar: {
                    horizontal: false,
                    columnWidth: '47%',
                    endingShape: 'flat'
                },
            },
            colors: ['<?php echo ($mode == 'night' ? '#6a6a6a' : '#9c27b0'); ?>'],
            xaxis: {
                    <?php if ($chart_type == 'This Week') { ?>
                        categories: [
                            'Saturday',
                            'Sunday',
                            'Monday',
                            'Tuesday',
                            'Wednesday',
                            'Thursday',
                            'Friday'
                        ]
                    <?php } ?>
            },
            tooltip: {
                y: {
                    formatter: function (val) {
                        return val
                    }
                }
            }
        };

        var chart = new ApexCharts(
            document.querySelector("#comments-chart"),
            options
        );
        chart.render();
    }
}
comments();

//MESSAGES SENT CHART
function messages() {
    if ($('#messages-chart').length) {
        var options = {
            chart: {
                type: 'bar',
                fontFamily: "Viga",
                offsetX: -26,
                stacked: false,
                height: 195,
                width: '100%',
                toolbar: {
                    show: false
                }
            },
            dataLabels: {
                enabled: false
            },
            series: [{
                name: 'Messages Sent',
                data: [<?php echo $msg_array; ?>]
            }],
            plotOptions: {
                bar: {
                    horizontal: false,
                    columnWidth: '47%',
                    endingShape: 'flat'
                },
            },
            colors: ['<?php echo ($mode == 'night' ? '#6a6a6a' : '#00a8f6'); ?>'],
            xaxis: {
                    <?php if ($chart_type == 'This Week') { ?>
                        categories: [
                            'Saturday',
                            'Sunday',
                            'Monday',
                            'Tuesday',
                            'Wednesday',
                            'Thursday',
                            'Friday'
                        ]
                    <?php } ?>
            },
            tooltip: {
                y: {
                    formatter: function (val) {
                        return val
                    }
                }
            }
        };

        var chart = new ApexCharts(
            document.querySelector("#messages-chart"),
            options
        );
        chart.render();
    }
}
messages();

//NEW MEMBERS CHART
function members() {
    if ($('#members-chart').length) {
        var options = {
            chart: {
                type: 'bar',
                fontFamily: "Viga",
                offsetX: -26,
                stacked: false,
                height: 195,
                width: '100%',
                toolbar: {
                    show: false
                }
            },
            dataLabels: {
                enabled: false
            },
            series: [{
                name: 'Members Join',
                data: [<?php echo $members_array; ?>]
            }],
            plotOptions: {
                bar: {
                    horizontal: false,
                    columnWidth: '47%',
                    endingShape: 'flat'
                },
            },
            colors: ['<?php echo ($mode == 'night' ? '#6a6a6a' : '#35ac20'); ?>'],
            xaxis: {
                    <?php if ($chart_type == 'This Week') { ?>
                        categories: [
                            'Saturday',
                            'Sunday',
                            'Monday',
                            'Tuesday',
                            'Wednesday',
                            'Thursday',
                            'Friday'
                        ]
                    <?php } ?>
            },
            tooltip: {
                y: {
                    formatter: function (val) {
                        return val
                    }
                }
            }
        };

        var chart = new ApexCharts(
            document.querySelector("#members-chart"),
            options
        );
        chart.render();
    }
}
members();

//POST LIKE CHART
function post_likes() {
    if ($('#post_likes-chart').length) {
        var options = {
            chart: {
                type: 'bar',
                fontFamily: "Viga",
                offsetX: -26,
                stacked: false,
                height: 195,
                width: '100%',
                toolbar: {
                    show: false
                }
            },
            dataLabels: {
                enabled: false
            },
            series: [{
                name: 'Post Likes',
                data: [<?php echo $post_likes_array; ?>]
            }],
            plotOptions: {
                bar: {
                    horizontal: false,
                    columnWidth: '47%',
                    endingShape: 'flat'
                },
            },
            colors: ['<?php echo ($mode == 'night' ? '#6a6a6a' : '#ff3380'); ?>'],
            xaxis: {
                    <?php if ($chart_type == 'This Week') { ?>
                        categories: [
                            'Saturday',
                            'Sunday',
                            'Monday',
                            'Tuesday',
                            'Wednesday',
                            'Thursday',
                            'Friday'
                        ]
                    <?php } ?>
            },
            tooltip: {
                y: {
                    formatter: function (val) {
                        return val
                    }
                }
            }
        };

        var chart = new ApexCharts(
            document.querySelector("#post_likes-chart"),
            options
        );
        chart.render();
    }
}
post_likes();
</script>