<?php
$active_users = $cpanel->activeUsers();
$inactive_users = $cpanel->inactiveUsers();
$deactivated_users = $cpanel->deactivatedUsers();

$ui = (!empty($_GET['ui-id'])) ? $_GET['ui-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? $cpanel::secure($_GET['query']) : '';
$filter_type    = '';
$link = '';
$search_link = '&';
$rang_link_href = '?';
$cpanel::$db->pageLimit  = 25;

if (!empty($filter_keyword)) {
    $link .= '&query='.$cpanel::secure($filter_keyword);
    $rang_link_href =  '?query='.$cpanel::secure($filter_keyword)."&";
    $sql   = " {$filter_type} (username LIKE '%$filter_keyword%' OR email LIKE '%$filter_keyword%' OR user_id = '$filter_keyword' OR fname LIKE '%$filter_keyword%' OR lname LIKE '%$filter_keyword%') ";
    $cpanel::$db->where($sql);
}

$sort_link = $link;
$sort_array = array('DESC_i' => array('user_id' , 'DESC'),
                    'ASC_i'  => array('user_id' , 'ASC'),
                    'DESC_u' => array('username' , 'DESC'),
                    'ASC_u'  => array('username' , 'ASC'));
if (!empty($_GET['sort']) && in_array($_GET['sort'], array_keys($sort_array))) {
    $cpanel::$db->orderBy($sort_array[$_GET['sort']][0],$sort_array[$_GET['sort']][1]);
    $link .= "&sort=".$cpanel::secure($_GET['sort']);
    $rang_link .= "&sort=".$cpanel::secure($_GET['sort']);
}
else{
    $_GET['sort'] = 'DESC_i';
    $cpanel::$db->orderBy('user_id', 'DESC');
}

if (!empty($_GET['user_type']) && in_array($_GET['user_type'], array('active','inactive','online','offline', 'premium-members', 'verified-members', 'guys', 'ladies'))) {
    if ($_GET['user_type'] == 'active') {
        $cpanel::$db->where('active', 1);
        $cpanel::$db->pageLimit  = 30;
    }
    elseif ($_GET['user_type'] == 'online') {
        $cpanel::$db->where('last_seen', time() - 60, '<');
        $cpanel::$db->pageLimit  = 30;
    }
    elseif ($_GET['user_type'] == 'offline') {
        $cpanel::$db->where('last_seen', time() - 60, '<');
        $cpanel::$db->pageLimit  = 30;
    }
    elseif ($_GET['user_type'] == 'verified-members') {
        $cpanel::$db->where('verified', 1);
        $cpanel::$db->pageLimit  = 30;
    }
    elseif ($_GET['user_type'] == 'guys') {
        $cpanel::$db->where('gender', 'male');
        $cpanel::$db->pageLimit  = 30;
    }
    elseif ($_GET['user_type'] == 'ladies') {
        $cpanel::$db->where('gender', 'female');
        $cpanel::$db->pageLimit  = 30;
    }
}

$cpanel::$db->where('active', '0');
$users = $cpanel::$db->objectbuilder()->paginate(T_USERS, $ui);
$get_online_users    = $cpanel::$db->where('last_seen', time() - 60, '>')->getValue(T_USERS, 'COUNT(*)');
$get_offline_users   = $cpanel::$db->where('last_seen', time() - 60, '<')->getValue(T_USERS, 'COUNT(*)');

if (($ui > $cpanel::$db->totalPages) && !empty($_GET['ui-id'])) {
    header("Location: " . cpanel('inactive-users'));
    exit();
}

$mode = 'day';
if (!empty($_COOKIE['mode']) && $_COOKIE['mode'] == 'night') {
    $mode = 'night';
}
?>
<div class="row justify-content-between align-items-center mb-5">
    <div class="col flex-shrink-0 mb-5 mb-md-0">
        <h1 class="display-4 mb-0">Inactive Members</h1>
        <div class="text-muted">
            This are members that have not yet activated their account or their account after registration<br>
            Please re-send an activation code to the user if they did not recieve one. This only applies if email validation is on!
        </div>
    </div>
</div>
<!-- Colored status cards-->
<div class="row gx-5">
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-danger border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $inactive_users; ?></div>
                        <div class="card-text">Inactive Members</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/hibernate.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>
   <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-primary border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $active_users; ?></div>
                        <div class="card-text">Active Members</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/3d-movie.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-success border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $get_online_users; ?></div>
                        <div class="card-text">Online Members</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/elearning.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xxl-3 col-md-6 mb-5">
        <div class="card card-raised border-start border-danger border-4">
            <div class="card-body px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <div class="display-5"><?php echo $deactivated_users; ?></div>
                        <div class="card-text">Deactivated Users</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/close.png');?>" alt="..." style="height: 3.3rem;weight:3.3rem;" />
                </div>
                <div class="card-text">
                    <div class="d-inline-flex align-items-center"></div>
                </div>
            </div>
        </div>
    </div>
    
</div>
<div class="row gx-5">
    <!-- Revenue breakdown chart example-->
    <div class="col-lg-12 mb-5">
        <div class="card card-raised h-100 border-start border-<?php echo $me['dash_color']; ?> border-4">
            <div class="card-header bg-white px-4">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="me-4">
                        <h6 class="card-title">Inactive Members</h6>
                        <form method="get" action="<?php echo cpanel('inactive-users'); ?>">
                            <div class="row">
                                <div class="col-md-7">
                                    <div class="form-group form-float">
                                        <div class="form-line">
                                            <label class="form-label search-form">Search for Id, email, username e.t.c.</label>
                                            <input type="text" name="query" id="query" class="form-control" value="<?php echo (!empty($_GET['query'])) ? $_GET['query']: '';?>" autocomplete="off">
                                        </div>
                                    </div>
                                  </div>
                                  <div class="col-md-4">
                                    <label class="form-label search-form">Account Filter</label>
                                    <select class="form-control show-tick" id="user_type" name="user_type">
                                        <option value="all">All</option>
                                        <option value="guys" <?php echo ((!empty($_GET['user_type']) && $_GET['user_type'] == 'guys') ? 'selected' : ''); ?>>Guys</option>
                                        <option value="ladies" <?php echo ((!empty($_GET['user_type']) && $_GET['user_type'] == 'ladies') ? 'selected' : ''); ?>>Ladies</option>
                                    </select>
                                  </div>
                                  <div class="col-md-1">
                                     <div class="form-group form-float">
                                        <div class="form-line">
                                            <label class="col-md-12 p-0 mb-3" for="priceto"></label>
                                            <button class="btn btn-outline-primary" id="Search">Search</button>
                                        </div>
                                     </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                    <div class="d-flex gap-2 me-n2">
                        <img src="<?php echo cpanel('si/img/icons/customer-service.png');?>" alt="..." style="height: 4rem" />
                    </div>
                </div>
            </div>
            <div class="card-body p-4">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        <div class="form-check">
                                            <input class="form-check-input check-all" id="check-all" type="checkbox"/>
                                            <label class="form-check-label" for="check-all"></label>
                                        </div>
                                    </th>
                                      <th>ID</th>
                                      <th>Profile</th>
                                      <th>Gender</th>
                                      <th>IP Address</th>
                                      <th>Account Code</th>
                                      <th>Last Seen</th>
                                      <th>Moderate</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php 
                                if (!empty($users)) {
                                    foreach ($users as $key => $context['user']) {
                                        $context['user'] = $cpanel->userData($context['user']);
                                        $context['user'] = o2array($context['user']);
                                        echo $cpanel->Senction('inactive-users/list');
                                    }
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="float-start">
                        <?php echo "Showing $ui out of " . $cpanel::$db->totalPages; ?> Pages
                    </div>
                    <div class="float-end">
                        <nav>
                            <ul class="pagination">
                                <li>
                                    <a class="text-decoration-none firstpage" href="<?php echo cpanel('inactive-users?ui-id=1').$link; ?>" data-ajax="?path=inactive-users&ui-id=1<?php echo($link); ?>">
                                        <i class="material-icons">first_page</i>
                                    </a>
                                </li>
                                <?php if ($ui > 1) {  ?>
                                <li>
                                    <a class="text-decoration-none previouspage" href="<?php echo cpanel('inactive-users?ui-id=' . ($ui - 1)).$link; ?>" data-ajax="?path=inactive-users&ui-id=<?php echo($ui - 1) ?><?php echo($link); ?>">
                                        <i class="material-icons">chevron_left</i>
                                    </a>
                                </li>
                                <?php  } ?>
                                <?php 
                                $nums       = 0;
                                $nums_uis = ($ui > 4) ? ($ui - 4) : $ui;
                                for ($i=$nums_uis; $i <= $cpanel::$db->totalPages; $i++) { 
                                    if ($nums < 8) {
                                ?>
                                <li class="<?php echo ($ui == $i) ? 'active' : ''; ?>">
                                    <a class="text-decoration-none" href="<?php echo cpanel('inactive-users?ui-id=' . ($i)).$link; ?>" data-ajax="?path=inactive-users&ui-id=<?php echo($i) ?><?php echo($link); ?>" class="waves-effect">
                                        <?php echo $i ?>   
                                    </a>
                                </li>
                                <?php } $nums++; }?>
                                <?php if ($cpanel::$db->totalPages > $ui) { ?>
                                <li>
                                    <a class="text-decoration-none nextpage" href="<?php echo cpanel('inactive-users?ui-id=' . ($ui + 1)).$link; ?>" data-ajax="?path=inactive-users&ui-id=<?php echo($ui + 1) ?><?php echo($link); ?>">
                                        <i class="material-icons">chevron_right</i>
                                    </a>
                                </li>
                                <?php } ?>
                                <li>
                                    <a class="text-decoration-none lastpage" href="<?php echo cpanel('inactive-users?ui-id=' . ($cpanel::$db->totalPages)).$link; ?>" data-ajax="?path=inactive-users&ui-id=<?php echo($cpanel::$db->totalPages) ?><?php echo($link); ?>">
                                        <i class="material-icons">last_page</i>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <div class="clearfix"></div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-lg-2 col-md-2">
                            <select class="form-control show-tick" id="action_type">
                                <option value="Delete">Delete Account</option>
                                <option value="Activate">Activate Account</option>
                            </select>
                        </div>
                        <div class="col-lg-3 col-md-3">
                            <button type="button" class="btn btn btn-outline-primary delete-selected d-block" disabled>Take Action<span></span></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>

<!-- Delete Single User -->
<div class="modal fade" id="DeleteModal" tabindex="-1" aria-labelledby="exampleModalCenteredLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenteredLabel">Delete This Member!</h5>
            </div>
            <div class="modal-body">Are you sure you want to delete this user from the community?</div>
            <div class="modal-footer">
                <button class="btn btn-outline-primary me-2" type="button" data-bs-dismiss="modal">Nope</button>
                <button class="btn btn-outline-danger" type="button">Yes Delete</button>
            </div>
        </div>
    </div>
</div>

<!-- Delete Multi Users -->
<div class="modal fade" id="SelectedDeleteModal" tabindex="-1" aria-labelledby="exampleModalCenteredLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenteredLabel">Delete users!</h5>
            </div>
            <div class="modal-body">Are you sure you want to delete the selected user(s) from the community? NOTE: All their uploaded media will be permanently removed!!</div>
            <div class="modal-footer">
                <button class="btn btn-outline-primary me-2" type="button" data-bs-dismiss="modal">Maybe Later</button>
                <button class="btn btn-outline-secondary" onclick="DeleteSelected()" type="button">Yes Delete All</button>
            </div>
        </div>
    </div>
</div>

<!-- Activate Account -->
<div class="modal fade" id="ActivateAcc" tabindex="-1" aria-labelledby="exampleModalCenteredLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenteredLabel">Account Action Confirmation!</h5>
            </div>
            <div class="modal-body">Are you sure you want to Activate this user's account?</div>
            <div class="modal-footer">
                <button class="btn btn-outline-dark me-2" type="button" data-bs-dismiss="modal">Nope Later</button>
                <button class="btn btn-outline-primary" type="button">Yes Go ahead</button>
            </div>
        </div>
    </div>
</div>

<!-- Deactivate Account -->
<div class="modal fade" id="DeactivateAcc" tabindex="-1" aria-labelledby="exampleModalCenteredLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenteredLabel">Account Action Confirmation!</h5>
            </div>
            <div class="modal-body">Are you sure you want to Deactivate this user's account?</div>
            <div class="modal-footer">
                <button class="btn btn-outline-dark me-2" type="button" data-bs-dismiss="modal">Nope Later</button>
                <button class="btn btn-outline-primary" type="button">Yes Go ahead</button>
            </div>
        </div>
    </div>
</div>

<!-- Delete Single User -->
<div class="modal fade" id="ResendModal" tabindex="-1" aria-labelledby="exampleModalCenteredLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenteredLabel">Resend Activation Code!</h5>
            </div>
            <div class="modal-body">Are you sure you want to resend the activation code to this user? The system will regenerate another code and send it</div>
            <div class="modal-footer">
                <button class="btn btn-outline-dark me-2" type="button" data-bs-dismiss="modal">Nope</button>
                <button class="btn btn-outline-primary" type="button" id="send">Yes Send</button>
            </div>
        </div>
    </div>
</div>

<!-- Delete User Posts -->
<div class="modal fade" id="DeletePosts" tabindex="-1" aria-labelledby="exampleModalCenteredLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenteredLabel">Delete Post Confirmation!</h5>
            </div>
            <div class="modal-body">Are you sure you want to Delete all this user's posts?</div>
            <div class="modal-footer">
                <button class="btn btn-outline-dark me-2" type="button" data-bs-dismiss="modal">Maybe Later</button>
                <button class="btn btn-outline-primary" type="button">Yes Go ahead</button>
            </div>
        </div>
    </div>
</div>

<!-- Add Followers to User -->
<div class="modal fade" id="AddFollowers" tabindex="-1" aria-labelledby="exampleModalCenteredLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenteredLabel">Add Followers!</h5>
            </div>
            <form class="add-followers" method="POST">
                <div class="modal-body">
                    How many followers do you want to add? <br>You can only add between <b>1</b> and <b><?php echo $cpanel::$db->getValue(T_USERS, "COUNT(*)") - 1;?></b> followers
                    <div class="clearfix"></div>
                    <hr>
                    <label class="form-label" class="main-label">Add More Followers</label><br>
                    <small class="admin-info">Enter the amount of followers you want to give this user!</small><br><br>
                    <mwc-textfield outlined class="w-100" type="number" id="followers" name="followers" label="How Many Followers?"></mwc-textfield>
                    <input type="hidden" id="user_id" name="user_id">
                </div>
                <div class="modal-footer">
                    <button class="btn btn-outline-dark me-2" type="button" onclick="HideModal()">Don't want to</button>
                    <button class="btn btn-outline-success" type="button">Add Followers</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
jQuery(document).ready(function($) {
        var range = { "Current": [moment().startOf('year') , moment().endOf('year')],
        "Today": [moment() , moment()], 
        "Yesterday": [moment().subtract(1, 'days') , moment().subtract(1, 'days')], 
        "This_Week": [moment().subtract(6, 'days') , moment()],
        "This_Month": [moment().startOf('month') , moment().endOf('month')],
        "Last_Month": [moment().subtract(1, 'month').startOf('month') , moment().subtract(1, 'month').endOf('month')],
        "This_Year": [moment().subtract(1, 'year').startOf('year') , moment().subtract(1, 'year').endOf('year')]}; 
        <?php 
        if (!empty($_GET['range']) && in_array($_GET['range'], array('Today','Yesterday','This Week','This Month','Last Month','This Year'))) { 
            if ($_GET['range'] == 'Today') { ?>
                var start = range.Today[0];
                var end = range.Today[1];
            <?php }elseif ($_GET['range'] == 'Yesterday') { ?>
                var start = range.Yesterday[0];
                var end = range.Yesterday[1];
            <?php }elseif ($_GET['range'] == 'This Week') { ?>
                var start = range.This_Week[0];
                var end = range.This_Week[1];
            <?php }elseif ($_GET['range'] == 'This Month') { ?>
                var start = range.This_Month[0];
                var end = range.This_Month[1];
            <?php }elseif ($_GET['range'] == 'Last Month') { ?>
                var start = range.Last_Month[0];
                var end = range.Last_Month[1];
            <?php }elseif ($_GET['range'] == 'This Year') { ?>
                var start = range.This_Year[0];
                var end = range.This_Year[1];
            <?php } ?>
        <?php } elseif (!empty($_GET['range']) && !empty($start) && !empty($end)) { ?>
            var start = "<?php echo($start) ?>";
            var end = "<?php echo($end) ?>";
        <?php } else{ ?>
            var start = range.Current[0];
            var end = range.Current[1];
        <?php } ?>

        function cb(start, end) {}
        $('#dashboard-daterangepicker').daterangepicker({
            startDate: start,
            endDate: end,
            opens: $('body').hasClass('rtl') ? 'right' : 'left',
            ranges: {
                'Current': [moment().startOf('year') , moment().endOf('year')],
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'This Week': [moment().subtract(6, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                'This Year': [moment().subtract(1, 'year').startOf('year'), moment().subtract(1, 'year').endOf('year')],
            }
        }, cb);
        cb(start, end);
        $(document).on('click', '.ranges ul li', function(event) {
            event.preventDefault();
            if ($(this).attr('data-range-key') != 'Custom Range') {
                $(document).off('click', '.ranges ul li');
                $('#redirect_link').attr('href', "<?php echo cpanel('inactive-users').$rang_link_href; ?>range="+$(this).attr('data-range-key'));
                $('#redirect_link').attr('data-ajax', "?path=inactive-users<?php echo($rang_link) ?>&range="+$(this).attr('data-range-key'));
                $('#redirect_link').click();
            }
        });
        $(document).on('click', '.applyBtn', function(event) {
            event.preventDefault();
            $(document).off('click', '.applyBtn');
            var text = $(this).parent('.drp-buttons').find('.drp-selected').html().toString();
            text = text.replaceAll("/", "_");
            $('#redirect_link').attr('href', "<?php echo cpanel('inactive-users').$rang_link_href; ?>range="+text);
            $('#redirect_link').attr('data-ajax', "?path=inactive-users<?php echo($rang_link) ?>&range="+text);
            $('#redirect_link').click();
        });
});
$('.check-all').on('click', function(event) {
    $('input:checkbox').not(this).prop('checked', this.checked);
});
$('.delete-checkbox, .check-all').change(function(event) {
    $('.delete-selected').attr('disabled', false);
    $('.delete-selected').find('span').text(' (' + $('.delete-checkbox:checked').length + ')');
});
$('.delete-selected').on('click', function(event) {
    event.preventDefault();
    action_type = $('#action_type').val();
    $('#SelectedDeleteModal').find('.modal-body').html('Are you sure you want to '+action_type+' the selected user(s)?');
    $('#SelectedDeleteModal').find('#exampleModalCenteredLabel').html(action_type+' this user(s) account!');
    $('#SelectedDeleteModal').find('.btn-outline-secondary').text('' + action_type + ' Accounts');
    $('#SelectedDeleteModal').modal('show');
});
function DeleteSelected() {
    action_type = $('#action_type').val();
    data = new Array();
    $('td input:checked').parents('tr').each(function () {
        data.push($(this).attr('data_selected'));
    });
    $('.delete-selected').attr('disabled', true);
    $('.delete-selected').text('Please wait...');
    $.post(cpanel_ajax_url('delete_multi_users'), {ids: data, type: action_type}, function () {
        if (action_type == 'Delete') {
            $.each( data, function( index, value ){$('#list-' + value).remove();});
            let notify_200 = {status: 'success',title: 'Inactive Users',text: 'Users account has been delected',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
            new Notify({ ...notify_200 });
            $('#SelectedDeleteModal').modal('hide');
            $('#redirect_link').attr('href', "<?php echo cpanel('inactive-users'); ?>");
            $('#redirect_link').attr('data-ajax', "?path=inactive-users");
            $('#redirect_link').click();
        } else if (action_type == 'Activate') {
            $('#redirect_link').attr('href', "<?php echo cpanel('inactive-users'); ?>");
            $('#redirect_link').attr('data-ajax', "?path=inactive-users");
            $('#redirect_link').click();
            let notify_success200 = {status: 'success',title: 'Inactive Users',text: 'Users account has been activated!',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
            new Notify({ ...notify_success200 });
            $('#SelectedDeleteModal').modal('hide');
        } else if (action_type == 'Deactivate') {
            $('#redirect_link').attr('href', "<?php echo cpanel('inactive-users'); ?>");
            $('#redirect_link').attr('data-ajax', "?path=inactive-users");
            $('#redirect_link').click();
            $('#SelectedDeleteModal').modal('hide');
            let notify_success201 = {status: 'success',title: 'Inactive Users',text: "We've deactivated the users account!",effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
            new Notify({ ...notify_success201 });
        } else {
            location.reload();
        }
        $('#SelectedDeleteModal').modal('hide');
        $('.delete-selected').text('Take Action');
    });
}
$('#Search').on('click', function(event) {
    event.preventDefault();
    var item = $('#query');
    var text = item.val();

    const accinput = $('#user_type');
    const AccType = accinput.val();
    $('#redirect_link').attr('href', "<?php echo cpanel('inactive-users').$rang_link_href; ?>query="+text+"&user_type="+AccType);
    $('#redirect_link').attr('data-ajax', "?path=inactive-users<?php echo($search_link); ?>query="+text+"&user_type="+AccType);
    $('#redirect_link').click();
});

function DeleteAcc(id, type = 'show') {
    let notify_error = {status: 'error',title: 'Inactive Users',text: 'Failed to delete this user. Try later!',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
    let notify_success = {status: 'success',title: 'Manage Users',text: 'User Delected Successfully!',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
    if (id == '') {
    return false;
    }
    if (type == 'hide') {
      $('#DeleteModal').find('.btn-outline-danger').attr('onclick', "DeleteAcc('"+id+"')");
      $('#DeleteModal').modal('show');
      return false;
    }
    $.post(cpanel_ajax_url('delete-user'), {id: id}, function(data, textStatus, xhr) {
        if (data.status == 200) {
        $('#list-' + id).fadeOut(500, function () {
            $(this).remove();
        });
        $('#DeleteModal').modal('hide');
        new Notify({ ...notify_success })
        } else {
            $('#DeleteModal').modal('hide');
            new Notify({ ...notify_error })
        }
    });
}

function Activate(id, type = 'show') {
    if (id == '') {
    return false;
    }
    if (type == 'hide') {
      $('#ActivateAcc').find('.btn-outline-primary').attr('onclick', "Activate('"+id+"')");
      $('#ActivateAcc').modal('show');
      return false;
    }
    $.post(cpanel_ajax_url('activate-account'), {id: id}, function(data, textStatus, xhr) {
        if (data.status == 200) {
            $('#ActivateAcc').modal('hide');
            $('#redirect_link').attr('href', "<?php echo cpanel('inactive-users'); ?>");
            $('#redirect_link').attr('data-ajax', "?path=inactive-users");
            $('#redirect_link').click();
            let notify_success201 = {status: 'success',title: 'Inactive Users',text: ''+ data.message + '',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
            new Notify({ ...notify_success201 });
        } else {
            $('#ActivateAcc').modal('hide');
            $('#redirect_link').attr('href', "<?php echo cpanel('inactive-users'); ?>");
            $('#redirect_link').attr('data-ajax', "?path=inactive-users");
            $('#redirect_link').click();
            let notify_error = {status: 'error',title: 'Inactive Users',text: ''+ data.error + '',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
            new Notify({ ...notify_error });
        }
    });
}

function Deactivate(id, type = 'show') {
    if (id == '') {
    return false;
    }
    if (type == 'hide') {
      $('#DeactivateAcc').find('.btn-outline-primary').attr('onclick', "Deactivate('"+id+"')");
      $('#DeactivateAcc').modal('show');
      return false;
    }
    $.post(cpanel_ajax_url('deactivate-account'), {id: id}, function(data, textStatus, xhr) {
        if (data.status == 200) {
            $('#DeactivateAcc').modal('hide');
            $('#redirect_link').attr('href', "<?php echo cpanel('inactive-users'); ?>");
            $('#redirect_link').attr('data-ajax', "?path=inactive-users");
            $('#redirect_link').click();
            let notify_success201 = {status: 'success',title: 'Inactive Users',text: ''+ data.message + '',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
            new Notify({ ...notify_success201 });
        } else {
            $('#DeactivateAcc').modal('hide');
            $('#redirect_link').attr('href', "<?php echo cpanel('inactive-users'); ?>");
            $('#redirect_link').attr('data-ajax', "?path=inactive-users");
            $('#redirect_link').click();
            let notify_error = {status: 'error',title: 'Inactive Users',text: ''+ data.error + '',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
            new Notify({ ...notify_error });
        }
    });
}

function ResendCode(id, type = 'show') {
    if (id == '') {return false;}
    if (type == 'hide') {
      $('#ResendModal').find('.btn-outline-primary').attr('onclick', "ResendCode('"+id+"')");
      $('#ResendModal').modal('show');
      return false;
    }
    $('#send').attr('disabled', true);
    $.post(cpanel_ajax_url('send-code'), {id: id}, function(data, textStatus, xhr) {
        if (data.status == 200) {  
            $('#ResendModal').modal('hide');
            $('#redirect_link').attr('href', "<?php echo cpanel('inactive-users'); ?>");
            $('#redirect_link').attr('data-ajax', "?path=inactive-users");
            $('#redirect_link').click();
            new Notify({ ...notify_success });
            let notify_success = {status: 'success',title: 'Inactive Users',text: ''+ data.message + '',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
        } else {
            $('#ResendModal').modal('hide');
            $('#send').removeAttr('disabled');
            $('#redirect_link').attr('href', "<?php echo cpanel('inactive-users'); ?>");
            $('#redirect_link').attr('data-ajax', "?path=inactive-users");
            $('#redirect_link').click();
            let notify_error = {status: 'error',title: 'Inactive Users',text: ''+ data.error + '',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
            new Notify({ ...notify_error });
        }
    });
}

function getUserId(user_id) { $('#user_id').val(user_id); }

$(function () {
    $('.delete-content').on('click', function(event) {
        event.preventDefault();
        $('#delete-modal').attr('data-id', $(this).attr('data-id')).modal('show');
    });
});
tippy('.lastpage', {arrow: false,content: 'Last Page'});
tippy('.nextpage', {arrow: false,content: 'Next Page'});
tippy('.previouspage', {arrow: false,content: 'Previous Page'});
tippy('.firstpage', {arrow: false,content: 'First Page'});
tippy('#verify', {arrow: false,content: 'Verified'});
tippy('.facebook', {arrow: false,content: 'Facebook Login'});
tippy('.google', {arrow: false,content: 'Google Login'});
tippy('.vkontakte', {arrow: false,content: 'Vkontakte Login'});
tippy('.twitter', {arrow: false,content: 'Twitter Login'});
tippy('.linkedIn', {arrow: false,content: 'linkedIn Login'});
tippy('.instagram', {arrow: false,content: 'Instagram Login'});
tippy('.discord', {arrow: false,content: 'Discord Login'});
tippy('.referrer', {arrow: false,content: 'Referrer Login'});
tippy('.fumigram', {arrow: false,content: '<?php echo $config['site_name']; ?> Login'});
</script>