<tr id="userad_<?php echo $context['ad']['id']?>" data-userad-id="<?php echo $context['ad']['id']?>" data_selected="<?php echo($context['ad']['id']) ?>">
  <td>
    <div class="form-check">
        <input class="form-check-input delete-checkbox" id="check-data-<?php echo($context['ad']['id']) ?>" type="checkbox" value="" />
        <label class="form-check-label" for="check-data-<?php echo($context['ad']['id']) ?>"></label>
    </div>
  </td>

   <td><?php echo $context['ad']['id']?></td>
   <td>
      <a class="text-decoration-none" href="<?php echo $context['ad']['url']; ?>" target="_blank"> 
        <?php echo $context['ad']['name']; ?>
      </a>
   </td>
   <td>
      <a href="<?php echo $context['user']['url']; ?>" target="_blank" class="text-decoration-none">
         <img src="<?php echo $context['user']['avatar']; ?>" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo($context['ad']['username']); ?>'s Profile" class="rounded-circle" alt="..." style="height: 2rem;weight:2rem;">
      </a>
      &nbsp; <?php echo $context['user']['username']; ?>
   </td>
   <td>
     <?php echo $context['ad']['appears']?>
   </td>
   <td>
     <div class="ajax-time" title="<?php echo date('c',$context['ad']['posted']); ?>">
         <?php echo time2str($context['ad']['posted']);?>
     </div>
   </td>
   <td>
     <?php echo $context['ad']['bidding']?>
   </td>
   <td>
     <?php echo $context['ad']['clicks']?>
   </td>
   <td>
     <?php echo $context['ad']['views']?>
   </td>
   <td>
     <?php echo $context['ad']['location']?>
   </td>
   <td>
    <?php if ($context['ad']['status'] == 1): ?>
      <span class="badge bg-success">Active</span>
      <?php else: ?>
      <span class="badge bg-danger">Inactive</span>
    <?php endif; ?>
   </td>
   <td>
      <div class="dropdown">
         <div class="btn btn-outline-primary dropdown-toggle" id="dropdownMenuDarkButton" data-bs-toggle="dropdown" aria-expanded="false">Action</div>
         <ul class="dropdown-menu" style="min-width: 10.5rem">
            <li><a class="dropdown-item" target="_blank" href="<?php echo $config['site_url']; ?>/edit_ad/<?php echo $context['ad']['id']?>">Edit Ad</a></li>
            <li><a class="dropdown-item delete-ad" href="javascript:void(0)" id="<?php echo $context['ad']['id']?>" onclick="DeleteAd('<?php echo($context['ad']['id']) ?>','hide');">Delete</a></li>
            <?php if ($context['ad']['status'] == 0): ?>
            <li><a class="dropdown-item" href="javascript:void(0)" onclick="Activate('<?php echo($context['ad']['id']) ?>', 'hide');">Activate</a></li>
            <?php elseif ($context['ad']['status'] == 1): ?>
            <li><a class="dropdown-item" href="javascript:void(0)" onclick="Deactivate('<?php echo($context['ad']['id']) ?>','hide');">Deactivate</a></li>
            <?php endif; ?>
         </ul>
      </div>
   </td>
</tr>