<?php
if($config['blog_system'] == 'off') {   
    header("Location: " . cpanel('overview'));
    exit();
}

$ui = (!empty($_GET['ui-id'])) ? $_GET['ui-id'] : 1;

$blog_categories = blog_categories();

?>
<div class="row justify-content-between align-items-center mb-5">
    <div class="col flex-shrink-0 mb-5 mb-md-0">
        <h1 class="display-4 mb-0">Blog Categories</h1>
        <div class="text-muted">
            Manage and add categories to the blog system.
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xxl-12 col-md-12 mb-12">
        <div class="card card-raised border-start border-<?php echo $me['dash_color']; ?> border-4">
            <div class="card-header bg-white px-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <div class="me-2">
                        <h2 class="card-title mb-0">Add New Category</h2>
                        <div class="card-subtitle">You can add a new category in all the languages at once!</div>
                    </div>
                    <img src="<?php echo cpanel('si/img/icons/menu.png');?>" alt="..." style="height: 3rem" />
                </div>
            </div>

            <div class="card-body">
                <form method="POST" id="add_category_form">
                    <div class="row">
                        <?php foreach (LangsNamesFromDB() as $key_) { ?>
                            <div class="col-md-2" id="normal-query-form">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <label class="form-label"><?php echo ucfirst($key_); ?></label>
                                        <input type="text" class="form-control" name="<?php echo($key_) ?>" autocomplete="off">
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                        <div class="clearfix"></div>
                        <div class="float-start"><br>
                            <button class="btn btn-outline-primary" type="submit" onclick="AddNewCategory();">Add Category</button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<br>

<div class="row gx-5">
    <!-- Revenue breakdown chart example-->
    <div class="col-lg-12 mb-5">
        <div class="card card-raised h-100 border-start border-<?php echo $me['dash_color']; ?> border-4">
            <!-- <div class="card-header bg-white px-4">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="me-4">
                        <h6 class="card-title">Categories</h6>
                        <div class="card-subtitle">&nbsp;</div>
                    </div>
                    <div class="d-flex gap-2 me-n2 mb-n4">
                        <label class="form-label" for="priceto">&nbsp;</label>
                        <img src="<?php echo cpanel('si/img/icons/categories.png');?>" alt="..." style="height: 3rem;weight:3rem;" />
                    </div>
                </div>
            </div> -->
            <div class="card-body p-4">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                            <thead>
                                 <tr>
                                    <th>
                                        <div class="form-check">
                                            <input class="form-check-input check-all" id="check-all" type="checkbox"/>
                                            <label class="form-check-label" for="check-all"></label>
                                        </div>
                                    </th>
                                      <th>ID</th>
                                      <th>Category Name</th>
                                      <th>Moderate</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php
                            $category_id = 1;
                            foreach ($blog_categories as $category_key => $category) {
                                $context['blog-categories'] = array('category_id' => $category_id, 'category_key' => $category_key, 'category' => $category);
                                echo $cpanel->Senction('blog-categories/list');
                                $category_id = $category_id + 1;
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="float-start">
                       
                    </div>
                    <div class="float-end">
                        <nav>
                            <ul class="pagination">
                                
                            </ul>
                        </nav>
                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-lg-3 col-md-3">
                            <button type="button" class="btn btn btn-outline-primary delete-selected d-block" disabled>Take Down<span></span></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>

<!-- Delete Single User -->
<div class="modal fade" id="DeleteModal" tabindex="-1" aria-labelledby="exampleModalCenteredLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenteredLabel">Delete category!</h5>
            </div>
            <div class="modal-body">Are you sure you want to delete this category?</div>
            <div class="modal-footer">
                <button class="btn btn-outline-primary me-2" type="button" data-bs-dismiss="modal">Nope</button>
                <button class="btn btn-outline-danger" type="button">Yes Delete</button>
            </div>
        </div>
    </div>
</div>

<!-- Delete Single User -->
<div class="modal fade" id="SelectedDeleteModal" tabindex="-1" aria-labelledby="exampleModalCenteredLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenteredLabel">Delete Categories!</h5>
            </div>
            <div class="modal-body">Are you sure you want to delete the selected categories?</div>
            <div class="modal-footer">
                <button class="btn btn-outline-dark me-2" type="button" data-bs-dismiss="modal">Nope</button>
                <button class="btn btn-outline-danger" type="button" onclick="DeleteSelected()">Yes Take Down</button>
            </div>
        </div>
    </div>
</div>

<style>
    .pagination > li > a .material-icons, .pagination > li > a .material-icons {vertical-align: middle;line-height: 26px;}
    .pagination > li > a, .pagination > li > a {min-width: 32px;border-radius: 16px;padding: 5px 4px !important;background: rgb(0 0 0 / 7%);display: block;text-align: center;margin: 0 2px;}
    .pagination li.active a {color: #fff;}
    .pagination .page-item.active .page-link {background: #e882a3;border-color: transparent;}
    .pagination .page-item .page-link:hover,
    .pagination .page-item .page-link:focus {text-decoration: none;}
    .pagination.pagination-rounded .page-item {margin: 0 5px;}
    .pagination.pagination-rounded .page-item .page-link {border-radius: 50%;padding: 0;display: flex;align-items: center;justify-content: center;height: 40px;width: 40px;}
    .pagination.pagination-rounded.pagination-sm .page-link {height: 30px;width: 30px;}
    .pagination.pagination-rounded.pagination-lg .page-link {height: 60px;width: 60px;}
    .pager li > a {-webkit-border-radius: 0;-moz-border-radius: 0;-ms-border-radius: 0;border-radius: 0;border: none;background-color: transparent;color: #222;font-weight: bold; }
    .pager li a:focus,
    .pager li a:active {background-color: transparent; }
    .pagination .disabled a,
    .pagination .disabled a:hover,
    .pagination .disabled a:focus,
    .pagination .disabled a:active {color: #bbb; }
    .pagination li.active a { color: #fff; background-color: var(--bs-blue); }
    .pagination li {-webkit-border-radius: 0;-moz-border-radius: 0;-ms-border-radius: 0;border-radius: 0; }.pagination li a:focus,.pagination li a:active {background-color: var(--bs-blue);color: #fff; }
    .no-data-found {margin-bottom: 20px;text-align: center;}
    .pagination > li > a {border: none;font-weight: bold;color: #555; }
    .pagination > li > a,
    .pagination > li > a {width: auto;height: 32px;-webkit-border-radius: 0;-moz-border-radius: 0;-ms-border-radius: 0;border-radius: 0; }.pagination > li > a .material-icons,.pagination > li > a .material-icons {position: relative;bottom: 2px; }
    .pagination-sm > li:first-child > a,
    .pagination-sm > li:last-child > a {width: 28px;height: 28px; }.pagination-sm > li:first-child > a .material-icons,.pagination-sm > li:last-child > a .material-icons {position: relative;top: -1px;left: -6px;font-size: 20px; }
    .pagination-lg > li:first-child > a,
    .pagination-lg > li:last-child > a {width: 44px;height: 44px; }.pagination-lg > li:first-child > a .material-icons,.pagination-lg > li:last-child > a .material-icons {font-size: 30px;position: relative;top: -3px;left: -10px; }
    nav ul:not(.list-unstyled) li a {padding: 10px;}
    .hidden{display: none;}
</style>
<script>
$('.check-all').on('click', function(event) {
    $('input:checkbox').not(this).prop('checked', this.checked);
});
$('.delete-checkbox, .check-all').change(function(event) {
    $('.delete-selected').attr('disabled', false);
    $('.delete-selected').find('span').text(' (' + $('.delete-checkbox:checked').length + ')');
});
$('.delete-selected').on('click', function(event) {
    event.preventDefault();
    $('#SelectedDeleteModal').modal('show');
});
function DeleteSelected() {
    data = new Array();
    $('td input:checked').parents('tr').each(function () {
        data.push($(this).attr('data_selected'));
    });
    $('.delete-selected').attr('disabled', true);
    $('.delete-selected').text('Please wait...');
    $.post(cpanel_ajax_url('remove_multi_blog_category'), {ids: data}, function () {
        $.each( data, function( index, value ){
            $("#list-"+value).remove();
        });
        $('#SelectedDeleteModal').modal('hide');
        let notify_success201 = {status: 'success',title: 'Blog Categories',text: 'Categories deleted Successfully!',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
        new Notify({ ...notify_success201 });
        $('#redirect_link').attr('href', "<?php echo cpanel('blog-categories'); ?>");
        $('#redirect_link').attr('data-ajax', "?path=blog-categories");
        $('#redirect_link').click();
        $('.delete-selected').text('Take Down');
    });
}

function DeleteCategory(key,type = 'show') {
    if (type == 'hide') {
        $('#DeleteModal').find('.btn-outline-danger').attr('onclick', "DeleteCategory('"+key+"')");
        $('#DeleteModal').modal('show');
        return false;
    }
    $.get(cpanel_ajax_url('delete_category'), {key:key}, function (data) {
        if(data.status == 200){
            $('#DeleteModal').modal('hide');
            $('#list-' + key).fadeOut(400, function () { $(this).remove();});
            $('#redirect_link').attr('href', "<?php echo cpanel('blog-categories'); ?>");
            $('#redirect_link').attr('data-ajax', "?path=blog-categories");
            $('#redirect_link').click();
            let notify_success201 = {status: 'success',title: 'Blog Categories',text: 'Category deleted Successfully!',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
            new Notify({ ...notify_success201 });
        }else{
            $('#DeleteModal').modal('hide');
            $('#redirect_link').attr('href', "<?php echo cpanel('blog-categories'); ?>");
            $('#redirect_link').attr('data-ajax', "?path=blog-categories");
            $('#redirect_link').click();
            let notify_error = {status: 'error',title: 'Blog Categories',text: 'Failed to delete this Category!',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
            new Notify({ ...notify_error });
        }
    });
}

    $('.btn-lang').on('click', function(event) {
        $('#defaultModal .modal-body form .data');
        var lang_id = $(this).attr('data-id');
        $.get(cpanel_ajax_url('get_lang_key'), {id: lang_id, lang_name: lang_id}, function(data, textStatus, xhr) {
            $('#defaultModal .modal-title').html('Edit Language key: ' + lang_id);
            $('#id_of_key').val(lang_id);
            $('#defaultModal .modal-body form .data').html(data.html);
        });
    });
    function SaveChanges() {
        $('.edit-key-settings').submit();
    }
    $(function () {
        var form_lang_settings = $('form.edit-key-settings');
        form_lang_settings.ajaxForm({
            url: cpanel_ajax_url('update_lang_key'),
            beforeSend: function() {
                $('.btn-outline-secondary').text('Please wait...');
            },
            success: function(data) {
                if (data.status == 200) {
                    $('.btn-outline-secondary').text('Save Changes');
                    var value_to_use = $('[data-editable=1]').val();
                    var id_of_key = $('#id_of_key').val();
                    $('#edit_' + id_of_key).text(value_to_use);
                    $('#defaultModal').modal('hide');
                    let notify_success201 = {status: 'success',title: 'Store Categories',text: 'Category Updated Successfully!',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
                    new Notify({ ...notify_success201 });
                    $('#redirect_link').attr('href', "<?php echo cpanel('blog-categories'); ?>");
                    $('#redirect_link').attr('data-ajax', "?path=blog-categories");
                    $('#redirect_link').click();
                }
            }
        });

        var form_category_settings = $('form#add_category_form');
        form_category_settings.ajaxForm({
            url: cpanel_ajax_url('add_new_category'),
            beforeSend: function() {
                form_category_settings.find('.btn-outline-primary').text('Please wait...');
            },
            success: function(data) {
                if (data.status == 200) {
                    form_category_settings.find('.btn-outline-primary').text('Add Category');
                    $('#redirect_link').attr('href', "<?php echo cpanel('blog-categories'); ?>");
                    $('#redirect_link').attr('data-ajax', "?path=blog-categories");
                    $('#redirect_link').click();
                    let notify_success201 = {status: 'success',title: 'Store Categories',text: '' + data.message + '',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
                    new Notify({ ...notify_success201 });
                }
                else{
                    form_category_settings.find('.btn-outline-primary').text('Add Category');
                    $('#redirect_link').attr('href', "<?php echo cpanel('blog-categories'); ?>");
                    $('#redirect_link').attr('data-ajax', "?path=blog-categories");
                    $('#redirect_link').click();
                    let notify_error = {status: 'error',title: 'Store Categories',text: 'Failed to add category. Please check your details!',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
                    new Notify({ ...notify_error });
                }
            }
        });
    });
</script>
<div class="modal fade" id="defaultModal" tabindex="-1" aria-labelledby="exampleModalCenteredLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content ">
            <div class="modal-header">
                <h4 class="modal-title" id="defaultModalLabel"></h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-success edit-lang-settings-alert" style="display:none;"></div>
                <form class="edit-key-settings" method="POST">
                    <div class="data"></div>
                    <input type="hidden" name="id_of_key" id="id_of_key" value="">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Close</button>&nbsp;&nbsp;
                <button type="button" class="btn btn-outline-secondary" onclick="SaveChanges()" data-dismiss="modal">Save Changes</button>
            </div>
        </div>
    </div>
</div>