<?php 

if ($me['manager'] == 0 && $me['admin'] == 0) {    
    header("Location: " . cpanel('overview'));
    exit();
}

$langs = $cpanel::Langs();
if (empty($_GET['id']) || !in_array($_GET['id'], array_keys( $langs))) {
    header("Location: " . cpanel('manage-langs'));
    exit();
}
$lang_name = $cpanel::secure($_GET['id']);
$ui = isset($_GET['ui-id']) ? $_GET['ui-id'] : 1;
$lang  = (!empty($_GET['id'])) ? $_GET['id'] : '';
$filter_keyword = (!empty($_GET['query'])) ? $cpanel::secure($_GET['query']) : '';
$cpanel::$db->pageLimit = 10;
$link = '';
$search_link = '&';
$rang_link_href = '?';
if (!empty($filter_keyword)) {
    $link = '&query='.$filter_keyword;
    $sql   = " (lang_key LIKE '%$filter_keyword%' OR ".$lang_name." LIKE '%$filter_keyword%') ";
    $cpanel::$db->where($sql);
} 
$langs    = $cpanel::$db->objectbuilder()->paginate(T_LANGS, $ui, array('lang_key',$cpanel::secure($_GET['id']),'id'));
if ($cpanel::$db->totalPages != 0) {
    if (($ui > $cpanel::$db->totalPages) && !empty($_GET['ui-id'])) {
        header("Location: " . cpanel('manage-langs'));
        exit();
    }
}
?>
<div class="row justify-content-between align-items-center mb-5">
    <div class="col flex-shrink-0 mb-5 mb-md-0">
        <h1 class="display-4 mb-0">Languages</h1>
        <div class="text-muted">You must learn how to translate languages before using this page!</div>
    </div>
</div>
<!-- Colored status cards-->
<div class="row">
    <div class="col-xxl-12 col-md-12 mb-12">
        <div class="card card-raised border-start border-<?php echo $me['dash_color']; ?> border-4">
            <div class="card-header bg-white px-4">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="me-4">
                        <h6 class="card-title">Translate & Updates Languages</h6>
                        <form method="get" action="<?php echo cpanel('edit-language'); ?>">
                            <div class="row">
                                <div class="col-md-11">
                                    <div class="form-group form-float">
                                        <div class="form-line">
                                            <label class="form-label search-form">You can search for language keyword and language names</label>
                                            <input type="text" name="query" id="query" class="form-control" value="<?php echo(!empty($filter_keyword) ? $filter_keyword : '') ?>" autocomplete="off">
                                            <input type="hidden" name="id" value="<?php echo($lang_name) ?>">
                                            <input type="hidden" name="ui-id" value="1">
                                        </div>
                                    </div>
                                  </div>
                                  <div class="col-md-1">
                                     <div class="form-group form-float">
                                        <div class="form-line">
                                            <label class="col-md-12 p-0 mb-3" for="priceto"></label>
                                            <button class="btn btn-outline-primary" id="Search-lang">Search</button>
                                        </div>
                                     </div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                    <div class="d-flex gap-2 me-n2">
                        <img src="<?php echo cpanel('si/img/icons/translator.png');?>" alt="..." style="height: 4rem" />
                    </div>
                </div>
            </div>

            <div class="card-body p-4">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Language Key Name</th>
                                    <th>Translated Language Value</th>
                                    <th>Moderate Language</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php
                                if (count($langs) > 0) {
                                    foreach ($langs as $row) {
                                        $context['lkey'] = $row->lang_key;
                                        $context['lval'] = $row->{"$lang_name"};
                                        $context['lid']  = $row->id;
                                        echo $cpanel->Senction('edit-language/list');
                                    }
                                }
                                else{
                                    echo $cpanel::createHtmlEl('tr',null,$cpanel::createHtmlEl('td',array(
                                        'colspan' => 4,
                                        'class' => 'empty-table text-center',
                                    ),"No language data found to display"));
                                } 
                                ?>
                            </tbody>
                        </table>
                    </div>
                    <div class="float-start">
                        <?php echo "Showing $ui out of " . $cpanel::$db->totalPages; ?> Pages!
                    </div>
                    <div class="float-end">
                        <nav>
                            <ul class="pagination">
                                <li>
                                    <a class="text-decoration-none firstpage" href="<?php echo cpanel("edit-language?id=".$lang_name."&ui-id=1").$link; ?>" data-ajax="?path=edit-language&id=<?php echo($lang_name); ?>&ui-id=1<?php echo($link); ?>">
                                        <i class="material-icons">first_page</i>
                                    </a>
                                </li>
                                <?php if ($ui > 1) {  ?>
                                <li>
                                    <a class="text-decoration-none previouspage" href="<?php echo cpanel("edit-language?id=".$lang_name."&ui-id=" . ($ui - 1)).$link; ?>" data-ajax="?path=edit-language&id=<?php echo($lang_name); ?>&ui-id=<?php echo($ui - 1) ?><?php echo($link); ?>">
                                        <i class="material-icons">chevron_left</i>
                                    </a>
                                </li>
                                <?php  } ?>
                                <?php 
                                $nums = 0;
                                $nums_pages = ($ui > 4) ? ($ui - 4) : $ui;
                                for ($i=$nums_pages; $i <= $cpanel::$db->totalPages; $i++) { 
                                    if ($nums < 8) {
                                    ?>
                                    <li class="<?php echo ($ui == $i) ? 'active' : ''; ?>"><a class="text-decoration-none" href="<?php echo cpanel("edit-language?id=".$lang_name."&ui-id=" . ($i)).$link; ?>" data-ajax="?path=edit-language&id=<?php echo($lang_name); ?>&ui-id=<?php echo($i) ?><?php echo($link); ?>" style="font-weight:500;"><?php echo $i ?></a></li>
                                    <?php
                                    }
                                    $nums++;
                                }
                                ?>
                                <?php if ($cpanel::$db->totalPages > $ui) { ?>
                                <li>
                                    <a class="text-decoration-none nextpage" href="<?php echo cpanel("edit-language?id=".$lang_name."&ui-id=" . ($ui + 1)).$link; ?>" data-ajax="?path=edit-language&id=<?php echo($lang_name); ?>&ui-id=<?php echo($ui + 1) ?><?php echo($link); ?>">
                                        <i class="material-icons">chevron_right</i>
                                    </a>
                                </li>
                                <?php } ?>
                                <li>
                                    <a class="text-decoration-none lastpage" href="<?php echo cpanel("edit-language?id=".$lang_name."&ui-id=" . ($cpanel::$db->totalPages)).$link; ?>" data-ajax="?path=edit-language&id=<?php echo($lang_name); ?>&ui-id=<?php echo($cpanel::$db->totalPages) ?><?php echo($link); ?>">
                                        <i class="material-icons">last_page</i>
                                    </a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                    <div class="clearfix"></div>
                    <!-- <span>&nbsp;</span> -->
                </div>   
        </div>
    </div>
</div>


<div class="modal fade" id="edit-lang-modal" tabindex="-1" aria-labelledby="exampleModalCenteredLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form id="edit-key-settings" method="POST">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalCenteredLabel">Edit language key: <span class="key"></span></h5>
                </div>
                <div class="modal-body">
                    <textarea style="resize: none;" name="val" class="form-control val" cols="20" rows="6"></textarea>             
                </div>
                <input type="hidden" name="id" value="" class="lang-id">
                <div class="modal-footer">
                    <button class="btn btn-outline-primary me-2" type="button" data-bs-dismiss="modal">Maybe Later</button>
                    <button class="btn btn-outline-success" type="submit">Save Changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<style>
    .pagination > li > a .material-icons, .pagination > li > a .material-icons {vertical-align: middle;line-height: 26px;}
    .pagination > li > a, .pagination > li > a {min-width: 32px;border-radius: 16px;padding: 5px 4px !important;background: rgb(0 0 0 / 7%);display: block;text-align: center;margin: 0 2px;}
    .pagination li.active a {color: #fff;}
    .pagination .page-item.active .page-link {background: #e882a3;border-color: transparent;}
    .pagination .page-item .page-link:hover,
    .pagination .page-item .page-link:focus {text-decoration: none;}
    .pagination.pagination-rounded .page-item {margin: 0 5px;}
    .pagination.pagination-rounded .page-item .page-link {border-radius: 50%;padding: 0;display: flex;align-items: center;justify-content: center;height: 40px;width: 40px;}
    .pagination.pagination-rounded.pagination-sm .page-link {height: 30px;width: 30px;}
    .pagination.pagination-rounded.pagination-lg .page-link {height: 60px;width: 60px;}
    .pager li > a {-webkit-border-radius: 0;-moz-border-radius: 0;-ms-border-radius: 0;border-radius: 0;border: none;background-color: transparent;color: #222;font-weight: bold; }
    .pager li a:focus,
    .pager li a:active {background-color: transparent; }
    .pagination .disabled a,
    .pagination .disabled a:hover,
    .pagination .disabled a:focus,
    .pagination .disabled a:active {color: #bbb; }
    .pagination li.active a { color: #fff; background-color: var(--bs-blue); }
    .pagination li {-webkit-border-radius: 0;-moz-border-radius: 0;-ms-border-radius: 0;border-radius: 0; }.pagination li a:focus,.pagination li a:active {background-color: var(--bs-blue);color: #fff; }
    .no-data-found {margin-bottom: 20px;text-align: center;}
    .pagination > li > a {border: none;font-weight: bold;color: #555; }
    .pagination > li > a,
    .pagination > li > a {width: auto;height: 32px;-webkit-border-radius: 0;-moz-border-radius: 0;-ms-border-radius: 0;border-radius: 0; }.pagination > li > a .material-icons,.pagination > li > a .material-icons {position: relative;bottom: 2px; }
    .pagination-sm > li:first-child > a,
    .pagination-sm > li:last-child > a {width: 28px;height: 28px; }.pagination-sm > li:first-child > a .material-icons,.pagination-sm > li:last-child > a .material-icons {position: relative;top: -1px;left: -6px;font-size: 20px; }
    .pagination-lg > li:first-child > a,
    .pagination-lg > li:last-child > a {width: 44px;height: 44px; }.pagination-lg > li:first-child > a .material-icons,.pagination-lg > li:last-child > a .material-icons {font-size: 30px;position: relative;top: -3px;left: -10px; }
    nav ul:not(.list-unstyled) li a {padding: 10px;}
    .hidden{display: none;}
</style>

<script>
$('.edit-lang-key').click(function(event) {
    var key = $(this).data('key');
    var lid = $(this).data('id');

    if(key && $.isNumeric(lid)){
        var val = $("#edit-lang-"+lid).text();
        var mod = $('#edit-lang-modal');

        mod.find('.key').text(key);
        mod.find('.lang-id').val(lid);
        mod.find('.val').val($.trim(val));
        mod.modal('show'); 
    }
});
jQuery(document).ready(function($) {
    $("form#edit-key-settings").submit(function(event) {
    event.preventDefault();
    var lid = $(this).find('.lang-id').val();
    var val = $(this).find('.val').val();
    var zis = $(this);
    var mod = $('#edit-lang-modal');

    zis.find('button[type="submit"]').attr('disabled', 'true');
    $.ajax({
        url: cpanel_ajax_url('edit-lang-key'),
        type: 'POST',
        dataType: 'json',
        data: {lang: '<?php echo($lang); ?>', id: lid, val: val },
        })
        .done(function(data) {
            if (data.status == 200) {
                let notify_error = {status: 'success',title: 'Translate Languages',text: ''+ data.message + '',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
                new Notify({ ...notify_error });
            }
            else{
                let notify_error = {status: 'warning',title: 'Translate Languages',text: ''+ data.message + '',effect: 'slide',speed: 600,customClass: '',customIcon: '',showIcon: true,showCloseButton: true,autoclose: true,autotimeout: 3000,gap: 20,distance: 20,type: 1,position: 'right bottom',customWrapper: ''}
                new Notify({ ...notify_error });
            }
            
            $("#edit-lang-"+lid).text(val);
            mod.modal('hide');
            setTimeout(function(){
                mod.find('.val').val('');
                mod.find('.key').text('');
                mod.find('.lang-id').val('');
                zis.find('button[type="submit"]').removeAttr('disabled');
                // $('#redirect_link').attr('href', "<?php echo cpanel("edit-language?id=".$lang_name) ?>");
                // $('#redirect_link').attr('data-ajax', "?path=edit-language&id=<?php echo($lang_name); ?>");
                // $('#redirect_link').click();
            },1000);
        });
    });
});
tippy('.lastpage', {
	arrow: false,
	content: 'Last Page',
});
tippy('.nextpage', {
	arrow: false,
	content: 'Next Page',
});
tippy('.previouspage', {
	arrow: false,
	content: 'Previous Page',
});
tippy('.firstpage', {
	arrow: false,
	content: 'First Page',
});

</script>