<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="d-xl-flex">
                        <div class="w-100">
                            <div class="p-lg-1">
                                <div id="intro" class="mb-5">
                                    <h4 class="mt-0 mb-4">Welcome to <?php echo $config['site_name']; ?></h4>
                                    <div style="width: 410px">
                                        <img src="<?php echo help('st/images/intro.jpg');?>" style="width:100%;height:100%;border-radius:8px">
                                    </div>
                                </div>
                            </div> 
                        </div>
                    </div>
                </div>
                <!--end card body-->
            </div> <!-- end card-->
        </div>
    </div>
    <!-- end row -->
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8462913288699097"
     crossorigin="anonymous"></script>
<!-- Help-Center -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8462913288699097"
     data-ad-slot="9094817199"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>