<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="d-xl-flex">
                        <div class="w-100">
                            <div class="p-lg-1">
                                <div id="intro" class="mb-5">
                                    <h4 class="mt-0 mb-4">Login Help</h4>
                                    <p>
                                        why can't i login to <?php echo $config['site_name']; ?>?
                                        <br><br>
                                        For now we are <b>Not</b> experiencing any issues or bugs with the login page and we would like it if you report any bugs you
                                        come accross when loging into your account. you can <b>DM</b> our official account with a screenshot of the bugs that's preventing you from loging in.
                                        <br><br>
                                        Or contact us from <a href="<?php echo $config['site_url'] ?>/contact_us" target="_blank" style="color: #ff0070;">here</a> with your screenshot and message.
                                        <br><br>
                                        We will add it here and do our best to help you overcome this issue.
                                        <br><br>
                                        <img src="<?php echo help('st/images/safety.png');?>" style="width:180px;height:180px;">
                                    </p>
                                </div>
                            </div> <!-- end padding-->
                        </div>

                        <!-- Start right-side-nav -->
                        <div class="d-none d-xl-block">
                            <div class="right-side-nav">
                                <ul class="nav nav-pills flex-column">
                                    <li class="nav-item">
                                        <a class="nav-link active">Notice</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!--end card body-->
            </div> <!-- end card-->
        </div>
    </div>
    <!-- end row -->
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8462913288699097" crossorigin="anonymous"></script>
    <!-- Help-Center -->
        <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8462913288699097" data-ad-slot="2211760360" data-ad-format="auto" data-full-width-responsive="true"></ins>
        <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
</div>