<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="d-xl-flex">
                        <div class="w-100">
                            <div class="p-lg-1">
                                <div id="intro" class="mb-5">
                                    <h3 class="mt-0 mb-4"> Privacy Policy</h3>
                                </div>
                                <p>
                                At <?php echo $config['site_name']; ?>, accessible from <b><?php echo $config['site_name']; ?></b>.com, one of our main priorities is the privacy of our visitors.
                                <br><br>
                                This privacy policy document contains types of information that is collected and recorded by <b><?php echo $config['site_name']; ?></b> and how we use those information to provide you with a much better experience on <b><?php echo $config['site_name']; ?></b>.
                                
                                <br><br>
                                If you have additional questions or require more information about our privacy policy, do not hesitate to contact us.
                                <br><br>
                                
                                This privacy policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in <b><?php echo $config['site_name']; ?></b>.
                                <br><br>
                                This policy is not applicable to any information collected offline or via channels other than this website.
                                <br>

                                <div id="Consent" class="mb-5">
                                    <h4 class="mt-0 mb-4"> Consent</h4>
                                    By using our website, you hereby consent to our privacy policy and agree to its terms.
                                </div>
                         

                                <div id="Information" class="mb-5">
                                    <h4 class="mt-0 mb-4"> Information we collect</h4>
                                    The personal information that you are asked to provide, and the reasons why you are asked to provide it, will be made clear to you at the point we ask you to provide your personal information.
                                    <br><br>
                                    If you contact us directly, we may receive additional information about you such as your name, email address, phone number, the contents of the message and/or attachments you may send us, and any other information you may choose to provide.
                                    <br><br>
                                    When you register for an Account, we may ask for your contact information, including items such as name, company name, address, email address, and telephone number.
                                </div>

                                <div id="useyourinfo" class="mb-5">
                                    <h4 class="mt-0 mb-4">  How we use your information</h4>
                                    We use the information we collect in various ways, including to:
                                    <br><br>
                                    <li>Provide, operate, and maintain our website</li>
                                    <li>Improve, personalize, and expand our website</li>
                                    <li>Understand and analyze how you use our website</li>
                                    <li>Send you emails</li>
                                    <li>Find and prevent fraud</li>
                                    <li>Develop new products, services, features, and functionality</li>
                                    <li>Communicate with you, either directly or through one of our partners, including for customer services</li>
                                    <li>Provide you with updates and other information relating to the website, and for marketing and promotional purposes</li>
                                </div>

                                <div id="LogFiles" class="mb-5">
                                    <h4 class="mt-0 mb-4"> Log Files</h4>
                                    <?php echo $config['site_name']; ?> follows a standard procedure of using log files.
                                    <br><br>
                                    These files log visitors when they visit websites. All hosting companies do this and a part of hosting services & analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks.
                                    <br><br>
                                    
                                    These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users movement on the website, and gathering demographic information.
                                </div>

                                <div id="Cookies" class="mb-5">
                                    <h4 class="mt-0 mb-4"> Cookies and Web Beacons</h4>
                                    Like any other website, <b><?php echo $config['site_name']; ?></b> uses 'cookies'. These cookies are used to store information including visitors preferences, and the pages on the website that the visitor accessed or visited.
                                    <br><br>
                                    The information is used to optimize the users experience by customizing our web page content based on visitors browser type and/or other information.
                                    <br><br>
                                    For more general information on cookies, please read <a href="#" target="_blank" style="color: #ff0070;">what are cookies.</a>
                                </div>

                                <div id="Advertising" class="mb-5">
                                    <h4 class="mt-0 mb-4"> Advertising Partners Privacy Policies</h4>
                                
                                    You may consult this list to find the Privacy Policy for each of the advertising partners of <b><?php echo $config['site_name']; ?></b>.
                                    <br><br>
                                    Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on <b><?php echo $config['site_name']; ?></b>, which are sent directly to users browser.
                                    <br><br>
                                    They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.
                                    <br><br>
                                    Note that <?php echo $config['site_name']; ?> has no access to or control over these cookies that are used by third-party advertisers.
                                </div>

                                <div id="ThirdParty" class="mb-5">
                                    <h4 class="mt-0 mb-4"> Third Party Privacy Policies</h4>
                                    
                                    <?php echo $config['site_name']; ?>'s Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options.
                                    <br><br>
                                    You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers\' respective websites.
                                </div>

                                <div id="CCPA" class="mb-5">
                                    <h4 class="mt-0 mb-4">CCPA Privacy Rights (Do Not Sell My Personal Information)</h4>
                          
                                    Under the CCPA, among other rights, California consumers have the right to:
                                    <br><br>
                                    Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.
                                    <br><br>
                                    Request that a business delete any personal data about the consumer that a business has collected.
                                    <br><br>
                                    Request that a business that sells a consumer's personal data, not sell the consumer's personal data.
                                    <br><br>
                                    If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.
                                </div>

                                <div id="GDPR" class="mb-5">
                                    <h4 class="mt-0 mb-4"> GDPR Data Protection Rights</h4>

                                    We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:
                                    <br><br>
                                    The right to access – You have the right to request copies of your personal data. <br>We may charge you a small fee for this service.
                                    <br><br>
                                    The right to rectification – You have the right to request that we correct any information you believe is inaccurate. <br>You also have the right to request that we complete the information you believe is incomplete.
                                    <br><br>
                                    The right to erasure – You have the right to request that we erase your personal data, under certain conditions.
                                    <br><br>
                                    The right to restrict processing – You have the right to request that we restrict the processing of your personal data, under certain conditions.
                                    <br><br>
                                    The right to object to processing – You have the right to object to our processing of your personal data, under certain conditions.
                                    <br><br>
                                    The right to data portability – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.
                                    <br><br>
                                    If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.
                                </div>

                                <div id="Children" class="mb-5">
                                    <h4 class="mt-0 mb-4">  Children's Information</h4>
                               
                                    Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.
                                    <br><br>
                                    <b><?php echo $config['site_name']; ?></b> does not knowingly collect any Personal Identifiable Information from children under the age of <b>13.</b>
                                    <br>If you think that your child provided this kind of information on our website, we strongly encourage you to <a href="<?php echo $config['site_url'] ?>/contact_us" target="_blank" style="color: #ff0070;">contact us</a> immediately and we will do our best efforts to promptly remove such information from our records.
                                </div>
                                </p>
                            </div> 
                        </div>

                        <!-- Start right-side-nav -->
                        <div class="d-none d-xl-block">
                            <div class="right-side-nav">
                                <ul class="nav nav-pills flex-column">
                                    <li class="nav-item">
                                        <a href="#intro" class="nav-link">Your Policy</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#Consent" class="nav-link">Consent</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#Information" class="nav-link">Information we collect</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#useyourinfo" class="nav-link">How we use your information</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#LogFiles" class="nav-link">Log Files</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#Cookies" class="nav-link">Cookies and Web Beacons</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#Advertising" class="nav-link">Advertising Partners</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#ThirdParty" class="nav-link">Third Party Policies</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#CCPA" class="nav-link">CCPA Privacy Rights</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#GDPR" class="nav-link">GDPR Data Protection</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#Children" class="nav-link">Children's Information</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!--end card body-->
            </div> <!-- end card-->
        </div>
    </div>
    <!-- end row -->
</div>