<tr id="list-<?php echo $cd['article']['id'];?>" data_selected="<?php  echo $cd['article']['id'];?>">
  <td>
   <div class="form-check">
      <input class="form-check-input delete-checkbox" id="check-data-<?php  echo $cd['article']['id'];?>" type="checkbox" value="" />
      <label class="form-check-label" for="check-data-<?php  echo $cd['article']['id'];?>"></label>
   </div>
  </td>
  <td><?php echo $cd['article']['id'];?></td>
  <td <?php $_from = $cpanel->getUserDataById($cd['article']['user_id']);?>>
      <a href="<?php echo $_from->url; ?>" target="_blank" class="text-decoration-none">
         <img src="<?php echo $_from->avatar?>" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo $_from->name; ?>'s Profile" class="rounded-circle" alt="..." style="height: 2rem;weight:2rem;">
      </a>
      &nbsp; <?php echo $_from->username; ?>
  </td>
  <td id="edit_<?php echo $cd['item']['id'];?>">
      <a class="text-decoration-none" href="<?php echo $config['site_url'] . '/blog/article/' . $cd['article']['id']; ?>" target="_blank">
         <img src="<?php echo(media($cd['article']['thumbnail'])); ?>" data-bs-toggle="tooltip" data-bs-placement="top" title="<?php echo $cd['article']['title'];?>" alt="..." style="border-radius:4px;height: 2.3rem;weight:2.3rem;">
      </a>
  </td>
  <td><?php echo $cd['article']['title'];?></td>
  <td><?php echo blog_categories()[$cd['article']['category']];?></td>
  <td><?php echo $cd['article']['view'];?></td>
  <td><?php echo(time2str($cd['article']['created_at'])); ?></td>
  <td>
      <a class="btn btn-outline-primary" href="<?php echo cpanel('edit-article?id=' . $cd['article']['id']); ?>"><i class="material-icons">edit</i></a>&nbsp;&nbsp;
      <a class="btn btn-outline-danger" href="javascript:void(0)" onclick="DeleteArticle(<?php echo $cd['article']['id']?>,'<?php echo $cd["article"]["thumbnail"]?>','hide');"><i class="material-icons">delete_outline</i></a>&nbsp;&nbsp;
      <?php if($cd['article']['posted'] == 1){?>
        <button class="btn btn-outline-dark" onclick="UnpublishArticle(<?php echo $cd['article']['id']?>,this);">UNPUBLISH</button>
      <?php }else{ ?>
        <button class="btn btn-outline-info" onclick="PublishArticle(<?php echo $cd['article']['id']?>,this);">PUBLISH</button>
      <?php } ?>
  </td>
</tr>