<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="d-xl-flex">
                        <div class="w-100">
                            <div class="p-lg-1">
                                <div id="intro" class="mb-5">
                                    <h4 class="mt-0 mb-4">Welcome to <?php echo $config['site_name']; ?></h4>

                                    <p>
                                        what is <?php echo $config['site_name']; ?>?
                                    </p>
                                    <p><b><?php echo $config['site_name']; ?></b> is an image sharing community fully built
                                        and designed for the world of <strong>anime</strong>
                                    </p>
                                    <p>
                                        We connect anime fans from across the world and accept anything animated.

                                        <?php echo $config['site_name']; ?> strongly believe's that Animation deserves to have their very own world 
                                        so that it will help with the bringing of anime fans and people alike together in one place.
                                    </p>

                                    <p>

                                    Yes there are a few out there which is used to watch, download and do a lot more for animation. <br>
                                    we agree that all this is indeed true. there are even discord communities, facebook pages and group, reddit communities etc.
 
                                    Despite knowing all that we have decided to provide our very own - Instagram like platform - that is based on anime and other related activities such as games, movies, manga etc...
                                    <br><br>
                                    We has purposely <b>disregard anything politices</b> news and other real life activities that is known to the world. <br>
                                    if you want all those things there are a lot of other companies out there such as Facebook, Twitter, Instagram and etc.
                                    <br><br>
                                    Our only purpose is to provide a Fun Zone for Anime fans to play and have fun.

                                    <div id="disregardPolitices" class="mb-5">
                                        <h4 class="mt-0 mb-4">Why disregard anything politices</h4>
                                        Fumigram is a company that is willing to provide it's community to the world of anime and Nothing Else.
                                        
                                        <br><br>
                                        We do not allow political related matter because they tend to rick havoc and we do not want to get ourselves involved with other companies problems because of politices.
                                        <br><br>
                                        Fumigram is a fun zone and it is only ment for such purposes. for politices related matters please see to companies listed above.
                                    </div>

                                
                                    <div id="PostBeingDeleted" class="mb-5">
                                        <h4 class="mt-0 mb-4">Post being deleted</h4>
                                        Posts that contain anything political related matter, real like news, e.t.c will be <b>deleted</b> without question if found.
                                        <br><br>
                                        Image that contains, blood, human flesh, death, etc. will be deleted without notice.<br>
                                        if user action is repeated by posting our list above! account will be <b>immediately deleted</b> and IP address will be blocked and banned from accessing our platform at <b><?php echo $config['site_name']; ?></b>.com.
                                        <br><br>
                                        we do not accept Appeals when your account has been deleted from our database.
                                        <br>
                                        Porn videos or images will be removed without question or notice and user account will be deleted & Ip address will be banned from accessing <b><?php echo $config['site_name']; ?></b>.com.
                                        <br><br>

                                        Images, videos, posts and e.t.c that contains human violence, discriminations, child abuse, child trafficking or any attempted act against children such act will not be torrlated and such post will be deleted without delay
                                        user responsible for carrying out such an act will be immediately banned.
                                        <br>
                                        We urge users to report any act of violence being carried out against others in the community.
                                    </div>

                              
                                    <div id="ReportAccounts" class="mb-5">
                                        <h4 class="mt-0 mb-4">Report other accounts</h4>
                                        Users that are reported for constantly violating our terms and conditions will be banned from using our service without question or appeal.
                                        <br><br>
                                        Users that are reported for carrying out act of violence against others will recieve a warning from our <b>official account.</b><br>
                                        Constant violation of this rules and regulations will result in a IP ban. 
                                        <br><br>
                                        This page will be constantly updated based on how we see things.
                                        <br><br>
                                        We're doing this to prevent future issues with the use of our services.
                                        <br><br>
                                        If you do not agree to this including our Terms and policies you're not to use this service.<br>
                                        Feel free to leave at anytime.
                                        once again we thanks you from joining <b><?php echo $config['site_name']; ?></b> and taking your time to read this. '_'
                                    </div>
                                    
                                 
                                    <div id="updated" class="mb-5">
                                    <h4 class="mt-0 mb-4">Page being updated</h4>
                                        This page will be updated with new rules in order to keep the community say and secure.
                                    </div>
                                    </p>
                                </div>
                            </div> 
                        </div>

                        <!-- Start right-side-nav -->
                        <div class="d-none d-xl-block">
                            <div class="right-side-nav">
                                <ul class="nav nav-pills flex-column">
                                    <li class="nav-item">
                                        <a href="#intro" class="nav-link"><?php echo $config['site_name']; ?></a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#disregardPolitices" class="nav-link">Disregard Politices</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#PostBeingDeleted" class="nav-link">Post being deleted</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#ReportAccounts" class="nav-link">Report other accounts</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#updated" class="nav-link">Page being updated</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!--end card body-->
            </div> <!-- end card-->
        </div>
    </div>
    <!-- end row -->
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8462913288699097"
     crossorigin="anonymous"></script>
<!-- Help-Center -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8462913288699097"
     data-ad-slot="9094817199"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>