<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="d-xl-flex">

                        <div class="w-100">
                            <div class="p-lg-1">

                                <div id="intro" class="mb-5">
                                    <h4 class="mt-0 mb-4">Signing up</h4>
                                </div>

                                <p>
                                <div id="Reservation" class="mb-5">
                                    <h4 class="mt-0 mb-4">Username already Taken</h4>
                                    
                                    I tried to register but It says username is already taken why?
                                    <br><br>
                                    Well as it says the username that you were using has already been used by another person but there are lots of spaces for new 
                                    usernames. it's highly recommended that you use another name or contact us. 
                                    <br><br>

                                    We will check to see if that user account is a dummy or a fake account. we will not take any action if that account is not a fake or dummy account. please keep that in mind.
                                </div>

                                <div id="Gmail" class="mb-5">
                                    <h4 class="mt-0 mb-4">Gmail.com</h4>
                                    
                                    I tried creating an account using other mails for example <b>kotlin@yahoo.com</b>
                                    but the system says to signup using <b>gmail.com</b> only. why is that?
                                    <br><br>

                                    We do not accept any other mailing services except gmail.com. this is to prevent fake emails and spam accounts.<br>
                                    The system has been purposely set to filter other mailing services. we are not removing this settings for the time being.
                                </div>

                                <div id="activation" class="mb-5">
                                    <h4 class="mt-0 mb-4">Did not recieve activation code?</h4>
                                    
                                    After creating my account I did not activation an code can I ask why?
                                    <br><br>

                                    Activation code is 6 in numbers. Something like this <b style="color:#ff0070;">57392</b>
                                    <br><br>

                                    We highly recommended that you check your inbox or spam folder for the activation code!<br>
                                    the probability of not receiving an activation code is very low but if you do come across that then don't hesitate to send us an email.
                                    we will also take more steps in preventing that from happening so do contact us if you fail to get your code.
                                    <br><br>
                                    We will send you an activation code.
                                </div>
                                </p>
                            </div> <!-- end padding-->
                        </div>

                        <!-- Start right-side-nav -->
                        <div class="d-none d-xl-block">
                            <div class="right-side-nav">
                                <ul class="nav nav-pills flex-column">
                                    <li class="nav-item">
                                        <a href="#intro" class="nav-link">Taking a username</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#Gmail" class="nav-link">Gmail.com</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#activation" class="nav-link">Activation code</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!--end card body-->
            </div> <!-- end card-->
        </div>
    </div>
    <!-- end row -->
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8462913288699097"
     crossorigin="anonymous"></script>
<!-- Help-Center -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8462913288699097"
     data-ad-slot="9094817199"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>